"""Drilling draft audit outputs (outputs/drilling/). Not the combined submission.

    draft_predictions.csv   one row per MDS invoice, in the template's order and columns
    invoice_audit.csv       the same rows with outcome, total status, blank reasons, dependencies, conditional total
    findings.jsonl          every flagging finding with its evidence, citations, dependencies and confidence
    audit_summary.md        counts and the flagged invoices
    coverage.md             what was audited, line by line and check by check
    uncertainty_report.md   what could not be determined and why; readings awaiting approval
    sensitivity.md          every alternative reading measured against the audit
    review.md               the adversarial review (reporting.audit_review)

The entitlement queries (AMB-13) are one per call-off-dependent line; they are counted per invoice and service here,
not written line by line.
"""

import csv
import dataclasses
import io
import json
from collections import Counter
from pathlib import Path

from contractor_audit.domains.drilling.audit.categories import CATEGORY_INFO, CATEGORY_PRECEDENCE, Category, flags
from contractor_audit.domains.drilling.audit.models import LineStatus
from contractor_audit.domains.drilling.audit.policy import AUDIT_SWITCHES, WORKING_READINGS
from contractor_audit.domains.drilling.audit.runner import AuditReport
from contractor_audit.domains.drilling.ingestion.models import DrillingDataset
from contractor_audit.domains.drilling.reporting.audit_review import review_md
from contractor_audit.shared.findings import ConfidenceBand

NOTE = "_Generated by `contractor-audit run --domain drilling`; do not edit by hand. Drilling draft only — not the combined submission._"
TEMPLATE_COLUMNS = ["invoice_id", "flagged", "error_category", "expected_total_cents", "billed_total_cents", "confidence"]
FILES = ("draft_predictions.csv", "invoice_audit.csv", "findings.jsonl", "audit_summary.md", "coverage.md", "uncertainty_report.md",
         "sensitivity.md", "review.md")
ENTITLEMENT = Category.ENTITLEMENT_UNVERIFIED.value


def _m(cents) -> str:
    if cents is None:
        return "blank"
    sign = "-" if cents < 0 else ""
    return f"{sign}{abs(cents) // 100:,}.{abs(cents) % 100:02d}"


def _csv(header, rows) -> str:
    buf = io.StringIO()
    w = csv.writer(buf, lineterminator="\n")
    w.writerow(header)
    w.writerows(rows)
    return buf.getvalue()


def _json(obj) -> str:
    return json.dumps(obj, ensure_ascii=False, sort_keys=True, default=str)


def _table(header, rows) -> list[str]:
    out = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    if not rows:
        out.append("| " + " | ".join(["none"] + ["—"] * (len(header) - 1)) + " |")
    return out


def ordered(report: AuditReport, template_ids: list[str]):
    by_id = {o.result.invoice_id: o for o in report.outcomes}
    ids = [i for i in template_ids if i in by_id] + sorted(set(by_id) - set(template_ids))
    return [by_id[i] for i in ids]


def draft_predictions(outcomes) -> str:
    return _csv(TEMPLATE_COLUMNS, [[o.result.invoice_id, int(o.result.flagged), o.result.error_category,
                                    "" if o.result.expected_total_cents is None else o.result.expected_total_cents,
                                    o.result.billed_total_cents, f"{o.result.confidence:.2f}"] for o in outcomes])


def invoice_audit(outcomes) -> str:
    header = ["invoice_no", "flagged", "outcome", "total_status", "primary_category", "categories", "billed_total_cents",
              "expected_total_cents", "contract_total_cents", "conditional_total_cents", "confidence_band", "confidence", "blank_reasons",
              "flagging_findings", "entitlement_queries", "entitlement_services", "total_depends_on", "would_flag_under", "would_unflag_under",
              "observations"]
    rows = []
    for o in outcomes:
        flagging = [f for f in o.findings if flags(f.category)]
        queries = [f for f in o.findings if f.category == ENTITLEMENT]
        services = sorted({l.line.service_code for l in o.audit.lines if l.status is LineStatus.CONDITIONAL})
        rows.append([o.result.invoice_id, int(o.result.flagged), o.outcome.value, o.total_status, o.result.error_category,
                     ";".join(dict.fromkeys(f.category for f in flagging)), o.result.billed_total_cents,
                     "" if o.result.expected_total_cents is None else o.result.expected_total_cents,
                     "" if o.contract_total_cents is None else o.contract_total_cents,
                     "" if o.conditional_total_cents is None else o.conditional_total_cents,
                     o.band.value, f"{o.band.score:.2f}", ";".join(o.blank_reasons), len(flagging), len(queries), ";".join(services),
                     ";".join(o.total_depends_on), ";".join(o.would_flag_under), ";".join(o.would_unflag_under),
                     " | ".join(o.audit.observations)])
    return _csv(header, rows)


def findings_jsonl(outcomes) -> str:
    return "".join(_json(dataclasses.asdict(f)) + "\n" for o in outcomes for f in o.findings if flags(f.category))


def _flagged_rows(outcomes):
    rows = []
    for o in outcomes:
        if o.result.flagged:
            cats = ", ".join(dict.fromkeys(f.category for f in o.findings if flags(f.category)))
            rows.append([o.result.invoice_id, cats, _m(o.result.billed_total_cents), _m(o.result.expected_total_cents),
                         _m(o.conditional_total_cents), f"{o.band.value} ({o.band.score:.2f})", "; ".join(o.blank_reasons)])
    return rows


def audit_summary(report: AuditReport, outcomes) -> str:
    flagged = [o for o in outcomes if o.result.flagged]
    findings = [f for o in outcomes for f in o.findings if flags(f.category)]
    lines = ["# Audit summary — drilling", "", NOTE, "",
             f"{len(outcomes)} invoices and {sum(len(o.audit.lines) for o in outcomes)} lines audited against DDS-2025-118. "
             f"**{len(flagged)} flagged** ({len(flagged) / len(outcomes):.1%}); {len(findings)} flagging findings; "
             f"{sum(o.result.expected_total_cents is not None for o in flagged)} flagged invoices with a published corrected total.", "",
             "Readings: the approved readings (`artifacts/drilling/approved_readings.json`) and the contract text for pricing. "
             "The audit-phase readings were selected from the contract text and subsequently approved in the Phase 5 review "
             "(AMB-25 decided as evidence not provided); their original confidence grades and alternative sensitivities are retained "
             "(`uncertainty_report.md`, `sensitivity.md`)."
             + (f" Not yet approved: {', '.join(report.policy.awaiting_approval)} (working readings)." if report.policy.awaiting_approval else ""), ""]
    lines += _table(["switch", "reading", "source"], [[s, v, src] for s, v, src in report.policy.readings() if s in AUDIT_SWITCHES or src != "CONTRACT_TEXT"])
    lines += ["", "## Flagged invoices", ""]
    lines += _table(["Invoice", "Categories", "Billed (USD)", "Corrected (USD)", "Conditional (USD, not payable)", "Confidence", "Blank because"],
                    _flagged_rows(outcomes))
    lines += ["", "## By category (primary)", ""]
    primary = Counter(o.result.error_category for o in flagged)
    lines += _table(["category", "check", "invoices (primary)", "findings"],
                    [[c.value, CATEGORY_INFO[c].check.value, primary.get(c.value, 0), sum(f.category == c.value for f in findings)]
                     for c in CATEGORY_PRECEDENCE if flags(c.value) and (primary.get(c.value) or any(f.category == c.value for f in findings))])
    return "\n".join(lines) + "\n"


def coverage(report: AuditReport, outcomes, dataset: DrillingDataset) -> str:
    flagged = [o for o in outcomes if o.result.flagged]
    line_status = Counter(l.status.value for o in outcomes for l in o.audit.lines)
    findings = [f for o in outcomes for f in o.findings if flags(f.category)]
    queries = Counter()
    for o in outcomes:
        for l in o.audit.lines:
            if any(f.category == ENTITLEMENT for f in l.findings):
                queries[l.line.service_code] += 1
    observations = Counter()
    for o in outcomes:
        for l in o.audit.lines:
            for obs in l.observations:
                observations[(l.line.service_code, obs.split(" (")[0].split(":")[0] if "below the" not in obs else "billed below the record")] += 1
    by_check = Counter(f.check.value for f in findings)
    lines = ["# Audit coverage — drilling", "", NOTE, ""]
    lines += _table(["Measure", "Count"], [
        ["invoices audited", len(outcomes)], ["lines audited", sum(len(o.audit.lines) for o in outcomes)],
        ["Daily Drilling Reports available", len(dataset.reports)], ["flagged invoices", len(flagged)],
        ["unflagged invoices", len(outcomes) - len(flagged)], ["flagging findings", len(findings)],
        ["entitlement queries (AMB-13, do not flag)", sum(queries.values())],
        ["flagged with a published corrected total", sum(o.result.expected_total_cents is not None for o in flagged)],
        ["flagged with a blank corrected total", sum(o.result.expected_total_cents is None for o in flagged)]])
    lines += ["", "## Line status", "", "How each line's payable amount stands after the audit.", ""]
    meaning = {"DETERMINED": "payable amount established from contract and report (0 when not payable)",
               "CONDITIONAL": "payable only if the missing call-off confirms the claimed class or nomination (AMB-13)",
               "UNDETERMINED": "cannot be valued from the evidence", "INVOICE_LEVEL": "DS-900, valued on the invoice total"}
    lines += _table(["status", "lines", "meaning"], [[k, v, meaning[k]] for k, v in sorted(line_status.items())])
    lines += ["", "## Findings by check", ""]
    lines += _table(["check", "findings"], [[k, v] for k, v in sorted(by_check.items())])
    lines += ["", "## Entitlement queries by service (AMB-13)", "",
              "Each is a line whose price or eligibility needs the call-off; its billed figures were compared with the price the claimed "
              "class or nomination gives, and are consistent with it unless another finding says otherwise.", ""]
    lines += _table(["service", "lines"], sorted(queries.items()))
    lines += ["", "## Observations (not findings)", "",
              "A claim below what the record supports is not a finding: the guidelines give a consequence only for billing above the "
              "record (check 5), and the Company never pays more than is claimed.", ""]
    lines += _table(["service", "observation", "lines"], [[s, o, n] for (s, o), n in sorted(observations.items())])
    return "\n".join(lines) + "\n"


def uncertainty(report: AuditReport, outcomes) -> str:
    flagged = [o for o in outcomes if o.result.flagged]
    reasons = Counter(r for o in flagged for r in o.blank_reasons)
    band = Counter((o.result.flagged, o.band.value) for o in outcomes)
    lines = ["# Uncertainty report — drilling", "", NOTE, "",
             "## Audit-phase readings", "",
             "The Phase 1 register left five switches for the audit. Each was run at a working reading chosen from the contract text "
             "(never from billed amounts) and then decided by the user (prompts/drilling/08-audit-review-decisions.md). The grade is "
             "kept after approval: an approval records the decision, it does not remove the uncertainty. `sensitivity.md` measures "
             "every alternative.", ""]
    lines += _table(["switch", "ambiguity", "reading", "status", "grade", "basis"],
                    [[n, WORKING_READINGS[n].ambiguity, r.value, _status(n, r), WORKING_READINGS[n].band.value, WORKING_READINGS[n].basis]
                     for n, r in report.policy.audit.items()])
    timing = [(o.result.invoice_id, obs) for o in outcomes for obs in o.audit.observations]
    lines += ["", "## Submission date (AMB-25: EVIDENCE_NOT_PROVIDED)", "",
              "Clause 33 turns on when an invoice is submitted; the data carries an invoice date only, and the invoice date does not "
              "prove the submission date. No timing finding is raised from it and no submission date is inferred. The invoice-date "
              f"facts that would bear on Clause 33 are kept here as observations ({len(timing)}):", ""]
    lines += _table(["invoice", "observation"], timing)
    lines += ["", "## Corrected totals", "",
              "STRICT policy: a corrected total is published only when every line is valued from the contract and the reports, and no "
              "unapproved reading changes it. The call-offs are not in the data (AMB-13, approved as UNKNOWN / UNVERIFIED), and every "
              "invoice charges at least one class-rated service (MW-310 is on every report), so no invoice total is fully determined. "
              "The conditional total takes each call-off-dependent charge at the contractor's claimed class and nomination: it is kept "
              "in `invoice_audit.csv` for analysis and is never presented as payable.", ""]
    lines += _table(["blank reason (flagged invoices)", "invoices"], sorted(reasons.items(), key=lambda kv: -kv[1]))
    lines += ["", "## Confidence", "", "Evidence quality, not probability (HIGH 0.95, MEDIUM 0.75, LOW 0.55).", ""]
    lines += _table(["", "HIGH", "MEDIUM", "LOW"],
                    [["flagged"] + [band.get((True, b.value), 0) for b in ConfidenceBand],
                     ["unflagged"] + [band.get((False, b.value), 0) for b in ConfidenceBand]])
    lines += ["", "An unflagged invoice is MEDIUM at best: its class-rated charges are consistent with the class the contractor claims, "
              "but the call-off that would prove it is not in the data. It is LOW where the alternative of a LOW-graded reading would flag it (AMB-12 per well).", ""]
    return "\n".join(lines) + "\n"


def _status(switch: str, reading) -> str:
    if switch == "submission_date" and reading.value == "UNKNOWN_QUERY" and reading.approved:
        return "decided: EVIDENCE_NOT_PROVIDED (submission date unavailable)"
    return "APPROVED" if reading.approved else "WORKING (not approved)"


def sensitivity(report: AuditReport, outcomes) -> str:
    rows = [[r["switch"], r["working"] + (" (approved)" if r["working_approved"] else " (WORKING)"), r["alternative"], r["grade"],
             len(r["flags_added"]), len(r["flags_removed"]), r["findings_removed"], r["findings_added"], len(r["totals_changed"]),
             len(r["conditional_totals_changed"]), ", ".join(r["flags_removed"][:8]) + (" …" if len(r["flags_removed"]) > 8 else "")]
            for r in report.measured.rows]
    below = Counter()
    for o in outcomes:
        for l in o.audit.lines:
            if any("below the" in obs for obs in l.observations):
                below[l.line.service_code] += 1
    lines = ["# Sensitivity — drilling", "", NOTE, "",
             "Each row re-runs the whole audit with one reading flipped (only the services it can affect are repriced). "
             "`flags added` counts invoices the alternative would flag that the audit does not; `flags removed` the reverse. "
             "Nothing here changes the audit: approved readings stay as approved, and no reading was chosen for its fit to billing.", ""]
    lines += _table(["switch", "reading used", "alternative", "grade", "flags added", "flags removed", "findings removed",
                     "findings added", "totals changed", "conditional totals changed", "invoices it would clear"], rows)
    lines += ["", "## Claims below the approved reading's quantity", "",
              "Billed quantities below what the approved readings support are not findings (see `coverage.md`), so no reading's "
              "effect on them appears above. By service:", ""]
    lines += _table(["service", "lines billed below the supported quantity"], sorted(below.items()))
    lines += ["", "The same count under each alternative reading of the quantity rules (a reading under which the billing sits exactly on "
              "the record would show none):", ""]
    lines += _table(["switch", "alternative", "lines billed below the supported quantity"],
                    [[r["switch"], r["alternative"], ", ".join(f"{k} {v}" for k, v in r["below_record_lines"].items()) or "none"]
                     for r in report.measured.rows if r["switch"] in ("rig_up_hour", "dd120_hours", "metre_source", "appendix_g_reading")])
    lines += ["", "Reported, not acted on: the approved readings stand, and a claim below the record changes nothing payable.", ""]
    return "\n".join(lines) + "\n"


def write(report: AuditReport, dataset: DrillingDataset, template_ids: list[str], outputs_dir: Path) -> list[Path]:
    outcomes = ordered(report, template_ids)
    outputs_dir.mkdir(parents=True, exist_ok=True)
    texts = {
        "draft_predictions.csv": draft_predictions(outcomes),
        "invoice_audit.csv": invoice_audit(outcomes),
        "findings.jsonl": findings_jsonl(outcomes),
        "audit_summary.md": audit_summary(report, outcomes),
        "coverage.md": coverage(report, outcomes, dataset),
        "uncertainty_report.md": uncertainty(report, outcomes),
        "sensitivity.md": sensitivity(report, outcomes),
        "review.md": review_md(report, outcomes, dataset),
    }
    out = []
    for name in FILES:
        path = outputs_dir / name
        path.write_text(texts[name], encoding="utf-8", newline="\n")
        out.append(path)
    return out

