"""The drilling adversarial review (outputs/drilling/review.md), recomputed from the audit on every run.

Each inspection looks for the cases an audit gets wrong quietly: evidence charged twice under another date,
split lines, boundaries of thresholds and dates, Standby days, back-dated rates, rounding, blank or odd values,
invoices that reconcile despite a line error, and unusual invoices that are right. Every table is data, not prose,
so the review cannot go stale.
"""

from collections import Counter, defaultdict
from datetime import date, timedelta
from decimal import Decimal

from contractor_audit.domains.drilling.audit.categories import CATEGORY_INFO, CATEGORY_PRECEDENCE, flags
from contractor_audit.domains.drilling.audit.models import LineStatus
from contractor_audit.domains.drilling.ingestion.models import DrillingDataset
from contractor_audit.shared.findings import Check

CHECKS = {
    1: ("reference, issuer and period", "audit/invoices.py (invoice_checks); audit/lines.py (line well)", "test_contract_reference_and_issuer"),
    2: ("contract live on the work dates, term as extended", "audit/lines.py (term)", "test_work_after_the_extended_term"),
    3: ("inside its window, after the period closed", "audit/invoices.py (timing); audit/lines.py (period)", "test_invoice_timing; test_line_outside_period"),
    4: ("every line has its record, signed", "audit/lines.py (_record_checks, _record_consequence)", "test_missing_report; test_unsigned_report; test_record_part_missing"),
    5: ("quantities are the recorded ones", "audit/lines.py (_quantity, _match_pd210)", "test_quantity_above_record; test_metre_tolerance_25a"),
    6: ("each line identified against a priced item", "audit/lines.py (unit, description, report evidence)", "test_unsupported_service; test_unit_mismatch"),
    7: ("rate in force on the work date", "audit/lines.py (_expected_rate, 36A); audit/diagnosis.py", "test_wrong_rate_superseded; test_amendment_3_rate_before_and_after_issue"),
    8: ("adjustments in order, rounded, discounts from their date", "audit/diagnosis.py; audit/engine.py (36A adjustment)", "test_discount_and_factor_diagnosis; test_backdated_adjustment"),
    9: ("caps, exclusions, once-only, minimums", "audit/lines.py (_quantity, _match); pricing/quantity_rules.py", "test_standby_exclusion; test_daily_limit; test_once_only; test_minimum_hours"),
    10: ("nothing billed twice", "audit/lines.py (Ledger, _duplicate, resolve_deferred)", "test_duplicate_within_invoice; test_duplicate_across_invoices"),
    11: ("arithmetic reconciles, with what the contract adds or deducts", "audit/invoices.py; audit/lines.py (_arithmetic)", "test_line_and_invoice_arithmetic; test_ds900; test_vat"),
    12: ("outcome written down", "audit/results.py; reporting/audit_outputs.py", "test_real_audit_invariants"),
}


def _table(header, rows) -> list[str]:
    out = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    if not rows:
        out.append("| " + " | ".join(["none"] + ["—"] * (len(header) - 1)) + " |")
    return out


def _cats(o, line_ref=None):
    return ", ".join(dict.fromkeys(f.category for f in o.findings if flags(f.category) and (line_ref is None or f.line_ref == line_ref))) or "none"


def review_md(report, outcomes, dataset: DrillingDataset) -> str:
    by_inv = {o.result.invoice_id: o for o in outcomes}
    line_outcome = {l.line.line_ref: (o, l) for o in outcomes for l in o.audit.lines}
    everything = [f for o in outcomes for f in o.findings]
    findings = [f for f in everything if flags(f.category)]
    flagged = [o for o in outcomes if o.result.flagged]
    L = ["# Drilling audit review", "",
         "_Generated by `contractor-audit run --domain drilling`; do not edit by hand. Drilling draft only — not the combined submission._", "",
         "## 1. Guideline checklist", ""]
    L += _table(["Check", "Requirement", "Implemented in", "Tests (tests/drilling/test_audit_rules.py)", "Findings"],
                [[c, r, impl, t, sum(f.check.value == c for f in findings)] for c, (r, impl, t) in CHECKS.items()])
    L += ["", "## 2. Category matrix", ""]
    def effect(c):
        own = [f for f in everything if f.category == c.value]
        return ("changes it" if any(f.affects_total for f in own) else "blocks it (conditional line)" if any(f.blocks_total for f in own)
                else "none" if own else "—")
    L += _table(["Category", "Check", "Clauses", "Findings", "Invoices", "Effect on the total", "Flags"],
                [[c.value, CATEGORY_INFO[c].check.value, "; ".join(CATEGORY_INFO[c].clauses), sum(f.category == c.value for f in everything),
                  len({f.invoice_id for f in everything if f.category == c.value}), effect(c),
                  "yes" if CATEGORY_INFO[c].flags else "no (query)"] for c in CATEGORY_PRECEDENCE])

    L += ["", "## 3. Adversarial inspections", ""]
    # a/b/d: several lines on one report and code; across invoices; split lines
    groups = defaultdict(list)
    for l in dataset.lines:
        if l.report_ref and l.service_code not in ("PD-210",):
            groups[(l.report_ref, l.service_code)].append(l)
    multi = {k: v for k, v in groups.items() if len(v) > 1}
    rows = []
    for (rep, code), ls in sorted(multi.items()):
        invs = sorted({l.invoice_no for l in ls})
        kind = "within one invoice" if len(invs) == 1 else "across invoices"
        verdicts = "; ".join(f"{l.line_ref}: {_cats(line_outcome[l.line_ref][0], l.line_ref)}" for l in ls)
        rows.append([rep, code, kind, " + ".join(str(l.quantity) for l in ls), verdicts])
    L += ["### Several lines quoting the same report for the same service (PD-210 band splits excluded)", ""]
    L += _table(["report", "service", "where", "quantities", "verdict per line"], rows) + [""]
    pd_groups = defaultdict(list)
    for l in dataset.lines:
        if l.service_code == "PD-210" and l.report_ref:
            pd_groups[l.report_ref].append(l)
    pd_multi = {k: v for k, v in pd_groups.items() if len(v) > 1}
    pd_overlap = [k for k, v in pd_multi.items() if any(a.depth_from_m < b.depth_to_m and b.depth_from_m < a.depth_to_m
                                                        for i, a in enumerate(v) for b in v[i + 1:])]
    L += [f"PD-210: {len(pd_multi)} reports carry more than one PD-210 line; {len(pd_overlap)} of them with overlapping depth intervals. "
          "Distinct intervals on one day are allowed (cl. 29 exception, cl. 23 band split).", ""]
    # c: once-only per run / well
    once = Counter()
    for l in dataset.lines:
        if l.service_code in ("DD-140", "MB-701", "MB-702", "LW-430"):
            once[(l.well_name, l.service_code)] += 1
    L += ["### Repeated once-per-well and once-per-run items", ""]
    L += _table(["well", "service", "lines", "verdict"],
                [[w, c, n, "; ".join(f"{x.line_ref}: {_cats(line_outcome[x.line_ref][0], x.line_ref)}" for x in dataset.lines
                                     if x.well_name == w and x.service_code == c)] for (w, c), n in sorted(once.items()) if n > 1])
    once_by_code = Counter(line_outcome[f.line_ref][1].line.service_code for f in findings if f.rule == "limits.once_only")
    L += ["", f"Once-only findings by service: {dict(once_by_code) or 'none'}. Once-per-run items (DD-111 on a run's last day, LW-420 "
          f"on its first) charged on another day: {sum(n for c, n in once_by_code.items() if c in ('DD-111', 'LW-420'))}.", ""]
    # e: thresholds
    services_sum = {}
    for o in outcomes:
        services_sum[o.result.invoice_id] = sum(l.line.amount_cents for l in o.audit.lines if l.status is not LineStatus.INVOICE_LEVEL)
    near = sorted((i, s) for i, s in services_sum.items() if abs(s - 25000000) <= 250000)
    L += ["### Threshold boundaries", "",
          f"DS-900 (cl. 38, 'exceeds' 250,000.00): {sum(s > 25000000 for s in services_sum.values())} invoices exceed the threshold; "
          f"{sum(s == 25000000 for s in services_sum.values())} sit exactly on it. Within 1 per cent of it:", ""]
    L += _table(["invoice", "services sum", "DS-900 billed", "verdict"],
                [[i, f"{s / 100:,.2f}", f"{sum(l.line.amount_cents for l in by_inv[i].audit.lines if l.status is LineStatus.INVOICE_LEVEL) / 100:,.2f}",
                  _cats(by_inv[i])] for i, s in near])
    tol = [(o.result.invoice_id, l.line.line_ref, obs) for o in outcomes for l in o.audit.lines for obs in l.observations if "25A" in obs]
    L += ["", f"25A metre tolerance: {len(tol)} lines billed above the recorded metres but within 1 per cent (payable as charged); "
          f"{sum(f.rule == 'quantity.exceeds_record' and 'beyond the 1 per cent' in f.message for f in findings)} above it (findings).", ""]
    L += _table(["invoice", "line", "observation"], tol[:20]) + [""]
    # f/h: date boundaries
    boundaries = [date(2025, 7, 1), date(2026, 1, 1), date(2026, 2, 1), date(2026, 4, 1), date(2026, 7, 1), date(2026, 12, 31)]
    rows = []
    for b in boundaries:
        for d in (b - timedelta(days=1), b):
            ls = [l for l in dataset.lines if l.service_date == d]
            bad = [l for l in ls if any(flags(f.category) for f in line_outcome[l.line_ref][1].findings)]
            rows.append([d, len(ls), len(bad), ", ".join(sorted({f.category for l in bad for f in line_outcome[l.line_ref][1].findings if flags(f.category)}))])
    L += ["### Date and effective-date boundaries", "",
          "Lines on the day before and the day of each instrument's effective date and the final expiry (S1 2025-07-01, A1 2026-01-01, "
          "A3 2026-02-01, S2 2026-04-01, A2 2026-07-01, expiry 2026-12-31):", ""]
    L += _table(["service date", "lines", "lines with a finding", "categories"], rows)
    after = [l for l in dataset.lines if l.service_date and l.service_date > date(2026, 12, 31)]
    L += ["", f"Lines dated after the final expiry: {len(after)} ({', '.join(l.line_ref for l in after)}); each is `work_outside_contract_term`.", ""]
    issue = date(2026, 8, 17)
    around = [o for o in outcomes if o.audit.invoice.invoice_date and abs((o.audit.invoice.invoice_date - issue).days) <= 1]
    L += ["### Amendment No. 3 (issued 2026-08-17, effective 2026-02-01)", "",
          "Invoices dated the day before, on and after the date of issue:", ""]
    L += _table(["invoice", "dated", "adjustment billed", "verdict"],
                [[o.result.invoice_id, o.audit.invoice.invoice_date, f"{(o.audit.invoice.adjustment_cents or 0) / 100:.2f}", _cats(o)]
                 for o in sorted(around, key=lambda o: (o.audit.invoice.invoice_date, o.result.invoice_id))])
    retro_before = sum(1 for o in outcomes for l in o.audit.lines if l.retro_difference_cents is not None)
    L += ["", f"Lines for services on or after 2026-02-01 at an amended rate, invoiced before the issue (valued at the rate then in force, cl. 36A): "
          f"{retro_before}. Adjustment placed on: {', '.join(report.run.adjustment_invoices) or 'none'}.", ""]
    timing = [(o.result.invoice_id, obs) for o in outcomes for obs in o.audit.observations]
    L += ["### Submission timing (AMB-25)", "",
          f"The submission date is not in the data. {len(timing)} invoices are dated before their period ended or more than 30 days "
          "after it; with no submission date, Clause 33 is not judged and none is flagged for it (kept as observations):", ""]
    L += _table(["invoice", "observation", "other findings"], [[i, obs, _cats(by_inv[i])] for i, obs in timing]) + [""]
    # g: Standby
    standby = [l for l in dataset.lines if l.day_status == "Standby"]
    reports = {r.report_id: r for r in dataset.reports if r.report_id and r.operations}
    differ = [l for l in dataset.lines if l.report_ref in reports and l.service_date == reports[l.report_ref].date
              and ((l.day_status and l.day_status != reports[l.report_ref].operations.status)
                   or (l.hole_section and l.hole_section != reports[l.report_ref].operations.hole_section))]
    sb_bad = Counter(f.category for l in standby for f in line_outcome[l.line_ref][1].findings if flags(f.category))
    L += ["### Standby / Operating", "",
          f"{len(standby)} lines on Standby days; findings on them: {dict(sb_bad) or 'none'}. Every line's stated day status and hole "
          f"section were compared with its report: {len(differ)} differ "
          "(the day status used for pricing is always the report's, cl. 19).", ""]
    # i: rounding
    half = [l for l in dataset.lines if l.quantity is not None and l.unit_rate is not None and (l.quantity * l.unit_rate * 100) % 1 == Decimal("0.5")]
    half_bad = [l for l in half if any(f.category == "line_arithmetic" for f in line_outcome[l.line_ref][1].findings)]
    L += ["### Rounding", "",
          f"{len(half)} lines where quantity x rate falls exactly on half a cent (half-even decides); {len(half_bad)} of them are arithmetic findings. "
          f"VAT: {sum(1 for i in dataset.invoices if i.net_cents is not None and (i.net_cents * 15) % 100 == 50)} invoices with VAT exactly on half a cent.", ""]
    # j/k: unusual and missing values
    zero = [l.line_ref for l in dataset.lines if l.service_code != "DS-900" and (l.quantity is not None and l.quantity <= 0 or (l.amount_cents or 0) < 0)]
    blank_date = Counter(l.service_code for l in dataset.lines if l.service_date is None)
    blank_ref = Counter(l.service_code for l in dataset.lines if not l.report_ref)
    L += ["### Zero, negative and missing values", "",
          f"Service lines with a zero or negative quantity or amount: {len(zero)}. Blank service dates: {dict(blank_date) or 'none'}; "
          f"blank report references: {dict(blank_ref) or 'none'} (DS-900 is an invoice-level charge, cl. 38). Ingestion issues: "
          f"{dict(Counter(i.code for i in dataset.issues)) or 'none'}.", ""]
    # l: AMB-13
    cond = Counter(o.total_status for o in outcomes)
    differs = [f for f in everything if f.rule == "entitlement.descriptive_class_differs"]
    exceptions = sorted(o.result.invoice_id for o in outcomes if not o.result.flagged and o.conditional_total_cents != o.result.billed_total_cents)
    queries = [f for f in everything if f.category == "entitlement_unverified"]
    L += ["### Unresolved AMB-13 invoices", "",
          f"Total status: {dict(cond)}. Every invoice charges a class-rated service, so none has a determined total. "
          f"Entitlement queries: {len(queries)} on {len({f.invoice_id for f in queries})} invoices. "
          f"Class-rated charges billed at the rate of a class other than the one the invoice describes: {len(differs)} "
          f"({', '.join(f.line_ref for f in differs) or 'none'}); a non-flagging query, since the invoice's well class is descriptive "
          "(cl. 34, Appendix B) and the class is the call-off's (P2, P3). Unflagged invoices whose conditional total (at the described "
          f"class) differs from the billed total: {len(exceptions)} ({', '.join(exceptions) or 'none'}), exactly those with that query.", ""]
    # m: reconciling totals
    arith = {"invoice_arithmetic", "vat_error", "line_arithmetic", "invoice_discount_error"}
    reconciling = [o for o in flagged if not any(f.category in arith for f in o.findings if flags(f.category))]
    L += ["### Invoices whose billed arithmetic reconciles despite a line error", "",
          f"{len(reconciling)} of the {len(flagged)} flagged invoices add up exactly as billed (lines, net, DS-900, VAT, total) and are "
          "flagged only for what their lines charge: the arithmetic check alone would have passed them.", ""]
    # n: unusual but correct
    lih = [l for l in dataset.lines if l.service_code.startswith("LH-")]
    lih_ok = [l for l in lih if not any(flags(f.category) for f in line_outcome[l.line_ref][1].findings)]
    ds_ok = [o for o in outcomes if any(l.status is LineStatus.INVOICE_LEVEL for l in o.audit.lines)
             and not any(f.category == "invoice_discount_error" for f in o.findings)]
    band_split = [k for k, v in pd_multi.items() if k not in pd_overlap]
    L += ["### Unusual invoices left alone", "",
          f"- Lost-in-hole charges (up to 1.2 million USD a line): {len(lih)}, of which {len(lih_ok)} are exactly the Schedule 2D value converted "
          "and depreciated, and pass.",
          f"- Invoices carrying a DS-900 discount that is exactly right: {len(ds_ok)}.",
          f"- Reports with PD-210 split across depth bands on one day, on distinct intervals: {len(band_split)} (allowed, cl. 23 / 29).",
          f"- Standby-day charges at the standby percentage: {sum(1 for l in standby if not any(flags(f.category) for f in line_outcome[l.line_ref][1].findings))} pass.",
          f"- Charges below what the record supports (e.g. DD-120 one hour below the approved rig-up reading): "
          f"{sum(1 for o in outcomes for l in o.audit.lines if any('below the' in x for x in l.observations))} lines; not findings (see coverage.md).", ""]
    L += ["## 4. Sanity observation", "",
          f"{len(flagged)} of {len(outcomes)} invoices flagged ({len(flagged) / len(outcomes):.1%}). The task states that 5-8 per cent of invoices "
          "are wrong; this is reported only as an observation and was not used to create, remove or grade any finding.", ""]
    checks = Counter(f.check.value for f in findings)
    L += ["## 5. Invariants", "",
          f"- Every flagged invoice has a primary category: {all(o.result.error_category for o in flagged)}.",
          f"- Every finding has a clause and evidence: {all(f.clause and f.evidence for f in findings)}.",
          f"- No corrected total is published where an entitlement or a working reading changes it: "
          f"{all(o.result.expected_total_cents is None for o in outcomes if o.total_status != 'determined')}.",
          f"- Findings for every check with an applicable case: {', '.join(f'{c}: {checks.get(c, 0)}' for c in range(1, 12))}.",
          f"- Check {Check.OUTCOME_RECORDED.value}: every invoice has an outcome ({dict(Counter(o.outcome.value for o in outcomes))}).", ""]
    return "\n".join(L) + "\n"
