"""Phase 4 canonical pricing: every quantity priced under approved and contract-text readings only.

A summary plus a digest of every priced quantity (the full trace is regenerated by `pricing.engine.price`).
Totals are the contract value of report evidence, not invoice figures; nothing is compared with invoices.
"""

import hashlib
import json
from collections import Counter, defaultdict
from pathlib import Path

from contractor_audit.domains.drilling.pricing.models import PricingResult

JSON_NAME, MD_NAME = "phase4_canonical_pricing.json", "phase4_canonical_pricing.md"
GENERATED = (JSON_NAME, MD_NAME)
CONDITIONAL_NOTE = ("Rate calculated but not payable: what these quantities would be worth only if the evidence they lack (eligibility "
                    "under the call-off, AMB-13) were established. Excluded from the priced total and from every canonical figure.")
NOTE = ("Canonical pricing of report evidence under approved and contract-text readings only. Not an invoice figure: no invoice "
        "is compared, flagged or totalled. Invoice-level items (DS-900, VAT, the 36A adjustment, the 25A tolerance) are not included.")


def digest(result: PricingResult) -> str:
    h = hashlib.sha256()
    for p in sorted(result.priced, key=lambda p: p.qid):
        steps = ";".join(f"{s.name}:{s.output_cents}" for part in p.parts for s in part.steps)
        h.update(f"{p.qid}\t{p.status.value}\t{p.chargeable_quantity}\t{p.amount_cents}\t{p.amount_without_retroactive_cents}\t"
                 f"{p.conditional_amount_cents}\t{steps}\n".encode())
    return h.hexdigest()


def summary(result: PricingResult) -> dict:
    if not result.canonical:
        raise ValueError(f"not canonical: hypothetical readings {result.hypothetical_switches}")
    by_status = Counter(p.status.value for p in result.priced)
    by_service = defaultdict(lambda: defaultdict(int))
    for p in result.priced:
        by_service[p.service_code][p.status.value] += 1
        by_service[p.service_code]["amount_cents"] += p.amount_cents
    reasons = Counter((p.status.value, p.service_code, p.reason.split(";")[0]) for p in result.priced if p.status.value != "PRICED")
    flags = Counter(f.split(" (")[0].split(":")[0] for p in result.priced for f in p.flags if p.status.value == "PRICED")
    retro = [p for p in result.priced if p.amount_without_retroactive_cents is not None and p.status.value == "PRICED"]
    conditional = defaultdict(lambda: [0, 0])
    for p in result.priced:
        if p.conditional_amount_cents is not None:
            conditional[(p.service_code, p.reason)][0] += 1
            conditional[(p.service_code, p.reason)][1] += p.conditional_amount_cents
    return {"schema": "contractor-audit/drilling-phase4-canonical-pricing", "schema_version": "1.1", "note": NOTE, "canonical": True,
            "selection": [{"switch": n, "value": v, "source": s} for n, v, s in result.selection],
            "quantities": len(result.priced), "by_status": dict(sorted(by_status.items())),
            "priced_total_cents": result.total_cents(),
            "by_service": {k: dict(sorted(v.items())) for k, v in sorted(by_service.items())},
            "not_priced": [{"status": st, "service": sv, "reason": r, "count": c} for (st, sv, r), c in sorted(reasons.items())],
            "flags_on_priced_quantities": dict(sorted(flags.items())),
            "retroactive_amendment": {"priced_quantities_at_a_backdated_rate": len(retro),
                                      "amount_cents": sum(p.amount_cents for p in retro),
                                      "amount_at_rates_known_before_it_cents": sum(p.amount_without_retroactive_cents for p in retro)},
            "conditional_not_payable": {
                "note": CONDITIONAL_NOTE,
                "rows": [{"service": sv, "reason": r, "count": c, "conditional_amount_cents": a} for (sv, r), (c, a) in sorted(conditional.items())]},
            "priced_quantities_sha256": digest(result)}


def _money(cents: int) -> str:
    sign = "-" if cents < 0 else ""
    return f"{sign}${abs(cents) // 100:,}.{abs(cents) % 100:02d}"


def write(result: PricingResult, artifacts_dir: Path) -> list[Path]:
    data = summary(result)
    md = ["# Drilling Phase 4 — canonical pricing of report evidence", "", NOTE, "",
          f"- quantities: {data['quantities']:,}; by status {data['by_status']}",
          f"- priced total: {_money(data['priced_total_cents'])}",
          f"- flags on priced quantities (for the audit phase): {data['flags_on_priced_quantities']}",
          f"- back-dated rate (Amendment No. 3): {data['retroactive_amendment']['priced_quantities_at_a_backdated_rate']:,} quantities, "
          f"{_money(data['retroactive_amendment']['amount_cents'])} at the amended rate, "
          f"{_money(data['retroactive_amendment']['amount_at_rates_known_before_it_cents'])} at rates known before it",
          f"- digest of every priced quantity: `{data['priced_quantities_sha256']}`", "",
          "## Not priced", "", "| status | service | reason | count |", "|---|---|---|---|"]
    md += [f"| {r['status']} | {r['service']} | {r['reason']} | {r['count']:,} |" for r in data["not_priced"]]
    cond = data["conditional_not_payable"]
    md += ["", "## Conditional amounts (not payable)", "", cond["note"], "", "| service | reason | count | conditional amount |", "|---|---|---|---|"]
    md += [f"| {r['service']} | {r['reason']} | {r['count']:,} | {_money(r['conditional_amount_cents'])} |" for r in cond["rows"]]
    md += ["", "## By service", "", "| service | priced | not chargeable | evidence not provided | unpriceable | amount |", "|---|---|---|---|---|---|"]
    md += [f"| {k} | {v.get('PRICED', 0):,} | {v.get('NOT_CHARGEABLE', 0):,} | {v.get('EVIDENCE_NOT_PROVIDED', 0):,} | {v.get('UNPRICEABLE', 0):,} | {_money(v['amount_cents'])} |"
           for k, v in data["by_service"].items()]
    out = []
    for name, text in ((JSON_NAME, json.dumps(data, indent=1) + "\n"), (MD_NAME, "\n".join(md) + "\n")):
        path = artifacts_dir / name
        path.write_text(text, encoding="utf-8", newline="\n")
        out.append(path)
    return out
