"""Phase 2 artifacts: the structural validation of the drilling data (JSON and a readable summary).

Observations are structural facts about the data, not audit findings. Written under artifacts/drilling/,
beside the other descriptive profiles; outputs/ stays reserved for audit results.
"""

import json
from collections import Counter
from pathlib import Path

from contractor_audit.domains.drilling.ingestion.models import DrillingDataset
from contractor_audit.domains.drilling.ingestion.validation import StructuralReport

JSON_NAME = "phase2_structural_validation.json"
MD_NAME = "phase2_structural_validation.md"
GENERATED = (JSON_NAME, MD_NAME)
SCHEMA = ("contractor-audit/drilling-structural-validation", "1.0")


def to_json(ds: DrillingDataset, rep: StructuralReport, evidence: tuple[dict, ...]) -> dict:
    grouped = rep.by_code()
    runs = rep.runs
    return {
        "schema": SCHEMA[0], "schema_version": SCHEMA[1],
        "note": "Structural observations about the drilling source data. None is an audit finding.",
        "sources": dict(sorted(ds.fingerprints.items())),
        "currency": {"value": ds.currency, "source": ds.currency_source},
        "counts": rep.counts,
        "report_variants": rep.variants,
        "summary": [{"code": code, "category": obs[0].category, "severity": obs[0].severity.value, "count": len(obs)}
                    for code, obs in grouped.items()],
        "observations": [{"code": o.code, "category": o.category, "severity": o.severity.value, "subject": list(o.subject),
                          "message": o.message, "evidence": o.evidence} for o in rep.observations],
        "ambiguity_evidence": list(evidence),
        "bha_runs": {"count": len(runs),
                     "runs_per_well": dict(sorted(Counter(Counter(w for w, _ in runs).values()).items())),
                     "with_discrepancies": sum(1 for r in runs.values() if r.discrepancies),
                     "recorded_equals_observed": sum(1 for r in runs.values() if (r.recorded_first, r.recorded_last) == (r.observed_first, r.observed_last)),
                     "days_per_run": {"min": min(r.observed_days for r in runs.values()), "max": max(r.observed_days for r in runs.values())} if runs else None},
        "wells": [{"well": t.well, "rigs": list(t.rigs), "fields": list(t.fields), "well_classes_stated": list(t.well_classes_stated),
                   "first_report": str(t.first_date) if t.first_date else None, "last_report": str(t.last_date) if t.last_date else None,
                   "reports": len(t.report_ids), "gaps": len(t.gaps), "invoices": [p.invoice_no for p in t.invoice_periods],
                   "overlapping_periods": [list(x) for x in t.overlapping_periods],
                   "period_days_without_report": len(t.period_days_without_report)} for t in rep.timelines.values()],
    }


def to_markdown(data: dict) -> str:
    c = data["counts"]
    lines = ["# Drilling Phase 2 — structural validation", "",
             "Generated by `build-artifacts --domain drilling`. " + data["note"] +
             " Whether any of them matters for billing is decided in the audit phases.", "",
             "## Counts", "",
             f"- invoices {c['invoices']:,}; lines {c['lines']:,}; daily reports {c['reports']:,}; wells {c['wells']}; BHA runs {c['bha_runs']:,}",
             f"- parse issues {c['parse_issues']} {c['parse_issues_by_severity']}",
             f"- service dates {c['service_dates'][0]} .. {c['service_dates'][1]}; report dates {c['report_dates'][0]} .. {c['report_dates'][1]}",
             f"- invoice date minus period end (days): {c['invoice_date_minus_period_end_days']}", "",
             "## Report variants (parts present)", "", "| parts | reports |", "|---|---|"]
    lines += [f"| {k} | {v:,} |" for k, v in data["report_variants"].items()]
    lines += ["", "## Observations by code", "", "| code | category | severity | count |", "|---|---|---|---|"]
    lines += [f"| {s['code']} | {s['category']} | {s['severity']} | {s['count']} |" for s in data["summary"]]
    lines += ["", "## Observations (all)", ""]
    for o in data["observations"]:
        if o["code"] == "REPEATED_REPORT_AND_CODE" and o["evidence"].get("distinct_depth_intervals"):
            continue
        lines.append(f"- `{o['code']}` {', '.join(o['subject'])}: {o['message']}")
    repeated = sum(1 for o in data["observations"] if o["code"] == "REPEATED_REPORT_AND_CODE" and o["evidence"].get("distinct_depth_intervals"))
    lines += [f"- ({repeated} `REPEATED_REPORT_AND_CODE` keys whose lines state distinct depth intervals are listed in the JSON only.)", "",
              "## BHA runs", "", f"{data['bha_runs']}", "", "## Evidence bearing on open Phase 1 ambiguities (recorded, not used to decide)", ""]
    for e in data["ambiguity_evidence"]:
        facts = {k: v for k, v in e.items() if k not in ("ambiguities", "fact")}
        lines.append(f"- **{', '.join(e['ambiguities'])}** {e['fact']} {facts}")
    lines += ["", "## Sources", ""] + [f"- `{k}` {v}" for k, v in data["sources"].items()] + [""]
    return "\n".join(lines)


def write(ds: DrillingDataset, rep: StructuralReport, evidence: tuple[dict, ...], artifacts_dir: Path) -> list[Path]:
    data = to_json(ds, rep, evidence)
    out = []
    for name, text in ((JSON_NAME, json.dumps(data, indent=1, ensure_ascii=False) + "\n"), (MD_NAME, to_markdown(data))):
        path = artifacts_dir / name
        path.write_text(text, encoding="utf-8", newline="\n")
        out.append(path)
    return out
