"""Markdown renderings of the Phase 1 artifacts.

Each renderer takes the same data that is written to JSON, so the human-readable
and machine-readable artifacts cannot drift apart.
"""

from collections import Counter, defaultdict

GENERATED = "_Generated by `contractor-audit build-artifacts --domain civil_works`; do not edit by hand._"


def _table(headers: list[str], rows: list[list]) -> str:
    def cell(v) -> str:
        return "" if v is None else str(v).replace("|", "\\|").replace("\n", " ")
    out = ["| " + " | ".join(headers) + " |", "|" + "---|" * len(headers)]
    out += ["| " + " | ".join(cell(v) for v in row) + " |" for row in rows]
    return "\n".join(out)


def _p(node: dict) -> str:
    return f"p.{node['source_page']}"


# --------------------------------------------------------------------------- contract extraction

def item_change_history(raw: dict) -> dict[str, list[dict]]:
    """Per item, every instrument provision that changes its rate or discount, in effective-date order."""
    history: dict[str, list[dict]] = defaultdict(list)
    for inst in raw["instruments"]:
        for row in inst.get("rate_substitutions", {}).get("rows", []):
            history[row["code"]].append(dict(effective=row["effective"], instrument=inst["id"], issued=inst["issued"],
                                             change=f"rate {row['rate_previously_payable']} -> {row['rate_payable']} per {row['unit']}",
                                             page=row["source_page"]))
        if "monthly_rates" in inst:
            m = inst["monthly_rates"]
            rates = ", ".join(f"{r['month']} {r['rate_payable']}" for r in m["rates"])
            history[m["code"]].append(dict(effective=m["rates"][0]["month"] + "-01", instrument=inst["id"], issued=inst["issued"],
                                           change=f"monthly rate ({m['index_name']}): {rates}; later months: {m['after_last_month']}",
                                           page=m["source_page"]))
        if "discount" in inst:
            d = inst["discount"]
            for item in d["items"]:
                history[item["code"]].append(dict(effective=d["effective"], instrument=inst["id"], issued=inst["issued"],
                                                  change=f"{d['percent']}% discount ({d['position_in_build_up']})",
                                                  page=d["source_page"]))
    for code in history:
        history[code].sort(key=lambda h: (h["effective"], h["issued"]))
    return dict(sorted(history.items()))


def render_contract_extraction(raw: dict) -> str:
    ag = raw["agreement"]
    s1, s2, s2a, s2b, s3, s4, s5 = (raw[k] for k in ("schedule_1", "schedule_2", "schedule_2a", "schedule_2b", "schedule_3", "schedule_4", "schedule_5"))
    out = [f"# Contract extraction — {raw['contract_ref']}", "", GENERATED, "",
           f"Source: `{raw['source_document']['path']}` ({raw['source_document']['page_count']} scanned pages, no text layer), "
           f"sha256 `{raw['source_document']['sha256'][:16]}…`. Machine-readable version: `contract_extraction.json`. "
           f"Review status of every value: `contract_verification.md`.", "",
           f"**Method.** {raw['extraction']['method']} {raw['extraction']['passes']}", ""]

    out += ["## A. Agreement", "", _table(["Term", "Value", "Page"], [
        [k.replace("_", " "), ", ".join(v["value"]) if isinstance(v["value"], list) else v["value"], v["source_page"]]
        for k, v in ag.items()]), ""]
    out += ["### Precedence rules stated in the contract", ""]
    out += [f"- {p['rule']} ({p['source_section']}, p.{p['source_page']})" for p in raw["precedence"]]
    out += ["", "### Definitions (Appendix A, p.34)", ""]
    out += [f"- **{d['term']}** — {d['definition']}" for d in raw["definitions"]]

    out += ["", "## B. Schedule 1 — Bill of Quantities (pp.17–19)", "", f"> {s1['source_text']}", ""]
    out += [f"> {n['source_text']} ({_p(n)})" for n in s1["notes"][1:]]
    out += ["", _table(["Code", "Series", "Description", "Unit", "Est. qty", "Base rate", "Page", "Note"], [
        [i["code"], i["series"], i["description"], i["unit"], i["estimated_quantity"], i["base_rate"], i["source_page"], i.get("rate_currency_note", "")]
        for i in s1["items"]]), ""]

    out += ["## C. Schedule 2 — Zone factors (p.20)", "", f"> {s2['source_text']}", "",
            _table(["Zone", "Description", "Factor"], [[z["zone"], z["description"], z["factor"]] for z in s2["zones"]]), "",
            f"Applies to series {', '.join(s2['applies_to_series'])}; not to series {', '.join(s2['excluded_series'])}.", "",
            "**Work areas** (the unit for Clauses 19, 31, 32, 44 and P6):", "",
            _table(["Work area", "Description"], [[w["work_area"], w["description"]] for w in s2["work_areas"]]), ""]

    out += ["## D. Schedule 2A — Indexed rates (p.21) and Clause 29A (p.32)", "", f"> {s2a['source_text']}", "",
            _table(["Code", "Description", "Schedule 1 base rate", "Unit"], [[i["code"], i["description"], i["base_rate"], i["unit"]] for i in s2a["items"]]), "",
            f"- Index: {s2a['index_name']}, base {s2a['base_index']} at {s2a['base_index_date']}.",
            f"- Formula (29A): {s2a['formula']['expression']}.",
            f"- Rounding: {s2a['rounding']['mode']} ('{s2a['rounding']['source_text']}').",
            f"- Data: {s2a['data_availability']['note']}", "",
            _table(["Month", "Index"], [[m["month"], m["index"]] for m in s2a["monthly_index"]]), ""]

    out += ["## E. Schedule 2B — Rates in USD (p.22) and Clause 26A (p.32)", "", f"> {s2b['source_text']}", "",
            _table(["Code", "Description", "Rate (USD per Schedule 2B)", "Unit"], [[i["code"], i["description"], i["usd_rate"], i["unit"]] for i in s2b["items"]]), "",
            f"- Conversion (26A): {s2b['conversion']['expression']}.",
            f"- Rounding: {s2b['rounding']['mode']}.",
            f"- Data: {s2b['data_availability']['note']}", "",
            _table(["Month", "Halalas per USD"], [[m["month"], m["halalas_per_usd"]] for m in s2b["monthly_fx"]]), ""]

    out += ["## F. Schedule 3 — Ground classification factors (p.23)", "", f"> {s3['source_text']}", "",
            _table(["Class", "Description", "Factor"], [[g["ground_class"], g["description"], g["factor"]] for g in s3["classes"]]), "",
            f"Applies only to: {', '.join(s3['applies_to_items'])}.", "", f"> {s3['notes'][0]['source_text']}", ""]

    nu, ru = s4["night_uplift"], s4["rest_day_uplift"]
    out += ["## G. Schedule 4 Parts 1–2 — Night and rest-day uplifts (p.24)", "", f"> {nu['source_text']}", "",
            _table(["Code", "Night uplift %"], [[i["code"], i["uplift_percent"]] for i in nu["items"]]), "",
            f"> {ru['source_text']}", "",
            _table(["Code", "Rest-day uplift %"], [[i["code"], i["uplift_percent"]] for i in ru["items"]]), "",
            "Conditions and interactions:", ""]
    out += [f"- {c['source_section']} ({_p(c)}): \"{c['source_text']}\"" for c in nu["conditions"] + ru["conditions"]]
    out += [f"- Build-up position: night uplift is step {nu['position_in_build_up']['step']}, rest-day uplift step {ru['position_in_build_up']['step']} of Clause 27.", ""]

    bq = s4["banded_quantities"]
    out += ["## H. Schedule 4 Part 3 — Banded quantities (pp.24–25)", "", f"> {bq['source_text']}", "",
            _table(["Code", "Unit", "Band as printed", "% of rate", "Page"],
                   [[i["code"], i["unit"], b["printed"], b["percent_of_rate"], b["source_page"]] for i in bq["items"] for b in i["bands"]]), "",
            f"Boundary wording: {bq['boundary_wording']['note']} (status {bq['boundary_wording']['review_status']}; see AMB-BANDS).", ""]

    dl = s4["daily_limits"]
    out += ["## I. Schedule 4 Parts 4–6 — Limits, exclusions, surveyed items (p.26)", "", f"> {dl['source_text']}", "",
            _table(["Code", "Limit", "Unit", "Per"], [[i["code"], i["limit"], i["unit"], i["per"]] for i in dl["items"]]), "",
            f"Consequence (Clause 31, p.6): \"{dl['consequence']['source_text']}\" — {dl['consequence']['consequence']}.", "",
            f"> {s4['mutually_exclusive']['source_text']}", "",
            _table(["Excluded item", "Excluded by", "Period (days)", "Scope"],
                   [[i["excluded_item"], i["excluded_by"], i["period_days"], i["scope"]] for i in s4["mutually_exclusive"]["items"]]), "",
            f"> {s4['surveyed_items']['source_text']}", "",
            f"Surveyed items: {', '.join(i['code'] for i in s4['surveyed_items']['items'])}. "
            f"Tolerance (33A, p.32): {s4['surveyed_items']['tolerance']['tolerance_percent']}% — \"{s4['surveyed_items']['tolerance']['source_text']}\".", ""]

    out += ["## J. Schedule 5 — Records required as a condition of payment (p.27)", "", f"> {s5['source_text']}", "",
            _table(["Code", "Record required", "Reference series"], [[i["code"], i["record_required"], i["reference_series"]] for i in s5["items"]]), "",
            f"- Week rule: \"{s5['week_rule']['source_text']}\"",
            f"- Signatures (Clause 47): \"{s5['signature_requirement']['source_text']}\"",
            f"- Content (Clause 47): \"{s5['content_requirement']['source_text']}\"",
            f"- Reference (Clause 47A): \"{s5['reference_requirement']['source_text']}\"",
            f"- Electronic form (P22): \"{s5['electronic_form']['source_text']}\"", "- Consequence when missing:"]
    out += [f"  - {c['source_section']} ({_p(c)}): \"{c['source_text']}\"" + (f" — {c['note']}" if c.get("note") else "") for c in s5["consequence_when_missing"]]

    s6, s7, s8 = raw["schedule_6"], raw["schedule_7"], raw["schedule_8"]
    out += ["", "## K. Schedule 6 — Daywork (pp.28–29)", "", f"> {s6['source_text']}", "",
            _table(["Labour grade", "Unit", "Rate"], [[x["grade"], x["unit"], x["rate"]] for x in s6["labour"]]), "",
            _table(["Plant", "Unit", "Rate"], [[x["plant"], x["unit"], x["rate"]] for x in s6["plant"]]), "",
            _table(["Percentage addition", "%"], [[x["category"], x["percent"]] for x in s6["percentage_additions"]]), "",
            f"> {s6['notes'][0]['source_text']}", "", f"In the billing data: {s6['used_in_billing_data']['note']}", ""]
    out += ["## L. Schedule 7 — Provisional and prime cost sums (p.30)", "", f"> {s7['source_text']}", "",
            _table(["Ref", "Description", "Kind", "Amount"], [[x["ref"], x["description"], x["kind"], x["amount"]] for x in s7["sums"]]), "",
            f"> {s7['notes'][0]['source_text']}", "", f"In the billing data: {s7['used_in_billing_data']['note']}", ""]
    out += ["## M. Schedule 8 — Preliminaries (p.31)", "", f"> {s8['source_text']}", "",
            _table(["Code", "Description", "Unit", "Amount"], [[x["code"], x["description"], x["unit"], x["amount"]] for x in s8["items"]]), ""]
    out += [f"> {n['source_text']}" for n in s8["notes"]]
    out += ["", f"In the billing data: {s8['used_in_billing_data']['note']}", ""]

    cy, ch, wk = raw["contract_years"], raw["chargeable_hour"], raw["week_definition"]
    out += ["## N. Contract years, chargeable hours, weeks", "", f"> 3A: {cy['source_text']}", "",
            _table(["Contract Year", "Start", "End", "Derivation"], [[y["year"], y["start"], y["end"], y["derivation"]] for y in cy["derived_years"]]), "",
            f"> 6A: {ch['source_text']}", "", f"Hour items: {', '.join(ch['hour_items'])}.", "",
            f"> 47A: {wk['source_text']}", "", f"Week items: {', '.join(wk['week_items'])}. {wk['note']}", ""]

    sv = raw["schedule_of_variations"]
    out += ["## O. Schedule of Variations (p.38)", "", f"> {sv['source_text']}", "",
            _table(["Instrument", "Issued", "Effective", "What it changes"], [[r["instrument"], r["issued"], r["effective"], r["what_it_changes"]] for r in sv["rows"]]), "",
            f"> {sv['term']['source_text']}", "", f"> {sv['note']['source_text']}", ""]

    out += ["## P. Supplements and amendments (pp.39–43)", ""]
    for inst in raw["instruments"]:
        out += [f"### {inst['name']} — `{inst['reference']}` (p.{inst['source_page']})", "",
                f"Issued **{inst['issued']}**, effective **{inst['effective']}**" + (" — **retroactive** (effective before issue)." if inst["retroactive"] else "."), "",
                f"> {inst['recital']['source_text']}", ""]
        if inst["recital"].get("note"):
            out += [f"Note: {inst['recital']['note']}", ""]
        if "completion_extension" in inst:
            ce = inst["completion_extension"]
            out += [f"**Extension of time:** completion to {ce['new_completion_date']} ({ce['extension_days']} days). \"{ce['source_text']}\"", ""]
        if "rate_substitutions" in inst:
            out += [f"**Substituted rates.** {inst['rate_substitutions']['source_text']}", "",
                    _table(["Code", "Description as printed", "Unit", "Previously payable", "Rate payable", "Effective"],
                           [[r["code"], r["description_as_printed"], r["unit"], r["rate_previously_payable"], r["rate_payable"], r["effective"]]
                            for r in inst["rate_substitutions"]["rows"]]), ""]
        if "monthly_rates" in inst:
            m = inst["monthly_rates"]
            out += [f"**Monthly rate for {m['code']}** ({m['index_name']}). {m['source_text']}", "",
                    _table(["Month of execution", "Rate payable"], [[r["month"], r["rate_payable"]] for r in m["rates"]]), ""]
        if "discount" in inst:
            d = inst["discount"]
            out += [f"**Discount {d['percent']}%** from {d['effective']} on {', '.join(i['code'] for i in d['items'])}. \"{d['source_text']}\"", ""]
        if inst.get("note"):
            out += [f"Note: {inst['note']}", ""]
        out += [f"Closing words: \"{inst['closing']['source_text']}\"", ""]

    out += ["### Precedence timeline", "", _table(["Date", "Event", "Source", "Page"],
                                                  [[t["date"], t["event"], t["instrument"], t["source_page"]] for t in raw["timeline"]]), ""]
    out += ["### Per-item instrument history (rates and discounts, by effective date)", "",
            "Items not listed keep their Schedule 1 base rate (subject to Schedules 2A/2B where listed). "
            "Where two instruments overlap, each instrument's closing words make the later-issued one govern work on or after its effective date.", ""]
    for code, hist in item_change_history(raw).items():
        base = next(i["base_rate"] for i in raw["schedule_1"]["items"] if i["code"] == code)
        out += [f"**{code}** (Schedule 1 base {base}):", ""]
        out += [f"- from {h['effective']}: {h['instrument']} (issued {h['issued']}, p.{h['page']}) — {h['change']}" for h in hist]
        out += [""]

    out += ["## Key clauses", "", "Clauses that decide measurement, pricing, records and payment. `verbatim` text is transcribed exactly; `paraphrase` marks a single-pass summary of lower-impact text.", ""]
    for c in raw["clauses"]:
        out += [f"- **{c['id']} {c['title']}** (p.{c['source_page']}, {c['text_form']}): {c['text']}" + (f" _Note: {c['note']}_" if c.get("note") else "")]

    out += ["", "## Documentary inconsistencies", ""]
    out += [f"- p.{d['source_page']} {d['source_section']}: {d['note']}" for d in raw["documentary_inconsistencies"]]
    out += ["", "## Ambiguities (readings preserved; none resolved here)", ""]
    for a in raw["ambiguities"]:
        out += [f"### {a['id']} — {a['topic']}", "",
                f"Pages {', '.join(map(str, a['source_pages']))}; impact **{a['impact']}**; status {a['review_status']}; guideline checks {a['affects_checks']}.", ""]
        out += [f"{n}. {r}" for n, r in enumerate(a["readings"], 1)]
        if a.get("note"):
            out += ["", a["note"]]
        out += [""]
    return "\n".join(out) + "\n"


# --------------------------------------------------------------------------- verification

def render_contract_verification(raw: dict, provenance_nodes: list[tuple[str, dict]], cross_check: dict) -> str:
    status_counts = Counter(n["review_status"] for _, n in provenance_nodes)
    passes_counts = Counter(n["review_passes"] for _, n in provenance_nodes)
    by_section: dict[str, Counter] = defaultdict(Counter)
    for path, node in provenance_nodes:
        top = path.split(".")[1].split("[")[0]
        by_section[top][(node["review_status"], node["review_passes"])] += 1

    out = ["# Contract verification — " + raw["contract_ref"], "", GENERATED, "",
           "Every value in `contract_extraction.json` carries `review_status` and `review_passes`. "
           "Invoice data was **not** used to confirm or correct any contract value: agreement with billed rates is not evidence of what the contract says.", "",
           "## Status definitions", ""]
    out += [f"- **{k}** — {v}" for k, v in raw["status_definitions"].items()]
    out += ["", "## Summary", "",
            _table(["Status", "Values"], [[s, status_counts.get(s, 0)] for s in raw["status_definitions"]]), "",
            _table(["Independent reads", "Values"], [[p, n] for p, n in sorted(passes_counts.items())]), "",
            "**UNREADABLE: none.** Every page of the scan was legible at 170–240 dpi; no value had to be guessed.", "",
            "## By section", "",
            _table(["Section", "VERIFIED ×2", "VERIFIED ×1", "AMBIGUOUS", "NOT_PROVIDED_IN_DATA"],
                   [[sec, c[("VERIFIED", 2)], c[("VERIFIED", 1)], sum(v for (s, _), v in c.items() if s == "AMBIGUOUS"),
                     sum(v for (s, _), v in c.items() if s == "NOT_PROVIDED_IN_DATA")] for sec, c in sorted(by_section.items())]), "",
            "## How high-impact values were verified", "",
            "High-impact values are BoQ codes, units and rates, zone and ground factors, uplifts, bands, daily limits, exclusions, surveyed items, "
            "Schedule 5 record requirements, the Schedule 2A index and Schedule 2B exchange rates, and every instrument date, rate, monthly rate and discount.", "",
            "1. **Pass 1** — every page was rendered at 130 dpi and schedule pages at 190 dpi, then transcribed into working notes.",
            "2. **Pass 2** — every table band was re-rendered at 240 dpi (greyscale, tighter crops) and each row re-read against the transcription.",
            "3. **Independent cross-check** — the JSON was typed separately from the pass-1 notes, then compared programmatically:", "",
            _table(["Table", "Rows compared", "Discrepancies"], [[k, v["rows"], v["discrepancies"]] for k, v in cross_check.items()]), "",
            "4. **Internal consistency checks** (contract-only, no invoice data):", "",
            "- Amendment No. 1: 27 Sep 2025 + 185 days = 31 Mar 2026 ✓. Amendment No. 2: 31 Mar 2026 + 183 days = 30 Sep 2026 ✓.",
            "- The 'rate previously payable' column of each instrument matches the rate in force before it: S1 B.23.010 4,120.00 = BoQ; "
            "A1 B.23.010 4,385.00 = S1; A1 E.54.010 876.00 = BoQ; S2 D.41.020 220.50 = S1 September 2025; A3 C.32.010 1,860.00 and A.14.010 53.20 = BoQ ✓.",
            "- The Schedule of Variations summary (p.38) agrees with every instrument page (issued/effective dates, items) ✓.",
            "- Appendix B example: A.12.020 34.80×1.06×1.375 = 50.721 → 50.72 ✓; A.14.020 22.40×1.06 = 23.744 → 23.74 ✓; "
            "total 15,794.40 ✓; retention 5% = 789.72 ✓; net 15,004.68 ✓. C.31.010 at 91.37 omits Schedule 2A indexation → AMB-INDEX-APPENDIX-B.",
            "- Every item code named in Schedules 2A, 2B, 3, 4, 5 and the instruments exists in Schedule 1 (enforced by `validate_extraction`).",
            "- Amendment No. 2 prints the same monthly rate for July and August 2026 (1,038.00); both passes read it the same way.", "",
            "## Single-pass values", "",
            "Values with `review_passes = 1` are low-impact narrative (Part I clauses 10 and 22–24, Part III 51–52, most of Parts IV and VI, "
            "Appendices A and C, the execution page) and Schedules 6–8, which no billed line uses. The loader rejects any high-impact value marked VERIFIED after one pass.", "",
            "## AMBIGUOUS — contract supports more than one reading", ""]
    for a in raw["ambiguities"]:
        if a["review_status"] == "AMBIGUOUS":
            out += [f"- **{a['id']}** ({a['impact']}) — {a['topic']} (pp.{', '.join(map(str, a['source_pages']))})"]
    amb_values = [(p, n) for p, n in provenance_nodes if n["review_status"] == "AMBIGUOUS"]
    if amb_values:
        out += ["", "Individual values flagged AMBIGUOUS:", ""]
        out += [f"- `{p}` (p.{n['source_page']}): {n.get('note', n['source_text'])}" for p, n in amb_values]
    out += ["", "## NOT PROVIDED IN DATA", ""]
    for a in raw["ambiguities"]:
        if a["review_status"] == "NOT_PROVIDED_IN_DATA":
            out += [f"- **{a['id']}** — {a['topic']}: {a.get('note', '')}"]
    for p, n in provenance_nodes:
        if n["review_status"] == "NOT_PROVIDED_IN_DATA":
            out += [f"- `{p}` (p.{n['source_page']}): {n.get('note', n['source_text'])}"]
    out += ["- Schedule 2A index and Schedule 2B exchange rates **are** provided for every month 2025-01 to 2026-12; no external lookup is needed.", "",
            "## UNREADABLE", "", "None.", ""]
    return "\n".join(out) + "\n"


# --------------------------------------------------------------------------- record inventory

def render_record_inventory(inv: dict) -> str:
    out = ["# Site record inventory — civil works", "", GENERATED, "",
           "Descriptive only: nothing here is a finding against an invoice.", "",
           f"**{inv['total_records']} records** parsed from `civilwork/records/*.txt`.", "",
           _table(["Type", "Title", "Records", "Date range"],
                  [[p, t["title"], t["count"], " to ".join(t["date_range"]) if t["date_range"] else ""] for p, t in inv["types"].items()]), "",
           "## Parse and format checks", "",
           f"- Parse issues: {inv['parse_issue_counts'] or 'none'}"]
    for code, msgs in inv["parse_issues"].items():
        out += [f"  - `{code}`: " + "; ".join(msgs[:10])]
    out += [f"- Malformed records (structural issues): {inv['malformed_records'] or 'none'}",
            f"- Duplicate ticket ids: {inv['duplicate_tickets'] or 'none'}",
            f"- Gaps in ticket numbering: {inv['ticket_numbering_gaps'] or 'none'}",
            f"- Records without a usable date: {inv['records_without_date'] or 'none'}",
            f"- Missing or blank foreman signature: {inv['missing_foreman_signature'] or 'none'}",
            f"- Missing or blank Engineer's-representative countersignature: {inv['missing_engineer_signature'] or 'none'}",
            f"- Job line values: {inv['jobs']}",
            f"- Foremen: {inv['foremen']}",
            f"- Engineer's representatives: {inv['engineer_reps']}", "",
            "## Format variants", "",
            "- All types: title line, `Ticket`, `Job`, `Area`, a free-text description line, `Signed (foreman)`, `Countersigned (Engineer's representative)`. Files use CRLF line endings.",
            "- Single-day types carry `Date: DD/MM/YYYY`. DX and PT additionally carry `Ground:`.",
            "- DW (weekly) carries `Week beginning: DD/MM/YYYY` and `Days on: Tue 04/02, ...` (day/month without year, resolved into the 7-day window).", ""]
    for p, t in inv["types"].items():
        out += [f"## {p} — {t['title']} ({t['count']})", "", f"Areas: {t['areas']}"]
        if t["ground"]:
            out += [f"", f"Ground stated: {t['ground']}"]
        if "days_on_count" in t:
            out += ["", f"Days on per record: {t['days_on_count']}; week-beginning weekday: {t['week_beginning_weekday']}"]
        out += ["", "Description phrasing (numbers masked as N):", "",
                _table(["Pattern", "Records", "Example"], [[d["pattern"], d["count"], d["example"]] for d in t["description_patterns"]]), ""]
    return "\n".join(out) + "\n"


# --------------------------------------------------------------------------- source profile

def render_source_profile(profile: dict, contract_ref: str) -> str:
    a, l, r, d, ar = (profile[k] for k in ("applications", "lines", "record_references", "date_relationships", "arithmetic"))
    out = ["# Source profile — civil works", "", GENERATED, "",
           "Descriptive only. Counts and cross-tabulations of the raw sources; no invoice is judged here. "
           "Comparisons against the contract are shown as agreement counts, not findings.", "",
           "## Applications (`applications.csv`)", "",
           _table(["Measure", "Value"], [
               ["applications", a["count"]], ["unique ids", a["unique_ids"]], ["duplicate ids", a["duplicate_ids"] or "none"],
               ["applications without lines", a["applications_without_lines"] or "none"],
               ["subcontractor", a["subcontractors"]],
               ["application_date range", " to ".join(a["application_date_range"])],
               ["period range", " to ".join(a["period_range"])],
               ["period length (days)", a["period_length_days"]],
               ["days from period_to to application_date", a["days_from_period_end_to_application"]],
               ["lines per application", a["lines_per_application"]],
               ["application_total (SAR)", a["application_total"]],
               ["retention (SAR)", a["retention"]],
               ["net_payable (SAR)", a["net_payable"]],
               ["non-zero adjustment", a["adjustment_nonzero"] or "none"],
               ["non-zero retention_released", a["retention_released_nonzero"] or "none"],
           ]), "",
           "### Contract references", "",
           _table(["contract_ref", "Applications", "Which"], [[ref, v["count"], ", ".join(v["applications"]) if v["applications"] else f"(the contract's own reference {contract_ref})"]
                                                           for ref, v in a["contract_refs"].items()]), "",
           f"Sites: {a['sites']}", "", f"Zones: {a['site_zones']}", "",
           "## Lines (`application_lines.csv`)", "",
           _table(["Measure", "Value"], [
               ["lines", l["count"]], ["unique line_ref", l["unique_line_refs"]],
               ["line_ref = application_no-line_no", l["line_ref_matches_application_and_line_no"]],
               ["lines without an application", l["lines_without_application"] or "none"],
               ["work_date range", " to ".join(l["work_date_range"])],
               ["work_date inside its application's period", l["work_date_inside_application_period"]],
               ["work_date outside its application's period", l["work_date_outside_application_period"]],
               ["line site = application site", l["line_site_equals_application_site"]],
               ["line zone = application zone", l["line_zone_equals_application_zone"]],
               ["distinct item codes", l["distinct_item_codes"]],
               ["item codes not in Schedule 1", l["item_codes_not_in_schedule_1"] or "none"],
               ["unit equals Schedule 1 unit", l["unit_agrees_with_schedule_1"]],
               ["description equals Schedule 1 description", l["description_agrees_with_schedule_1"]],
               ["quantity", l["quantity"]],
               ["night flag", l["night_flag"]],
               ["night flag × Schedule 4 Part 1 membership", l["night_flag_by_schedule_4_part_1_membership"]],
               ["work on a rest day (Fri/Sat)", l["rest_day_lines"]],
               ["ground class × Schedule 3 membership", l["ground_class_by_schedule_3_membership"]],
           ]), "",
           f"Units: {l['units']}", "", f"Work areas: {l['sites']}", "", f"Zones: {l['zones']}", "",
           f"Ground classes: {l['ground_classes']}", "", f"Weekday of work_date: {l['work_date_weekday']}", "",
           "### Per item", "",
           _table(["Code", "Lines", "Schedule 1 unit", "Billed units", "Qty sum", "Distinct rates", "Rate min", "Rate max", "With record_ref", "Night Y"],
                  [[i["code"], i["lines"], i["boq_unit"], i["billed_units"], i["quantity_sum"], i["distinct_rates"], i["rate_min"], i["rate_max"],
                    i["with_record_ref"], i["night_Y"]] for i in l["per_item"]]), "",
           "## Record references", "",
           _table(["Measure", "Value"], [
               ["lines with record_ref", r["lines_with_reference"]], ["lines without record_ref", r["lines_without_reference"]],
               ["distinct references", r["distinct_references"]], ["references resolving to a record file", r["references_resolving_to_a_record"]],
               ["references with no record file", r["references_without_record_file"] or "none"],
               ["lines quoting a missing record", r["lines_quoting_a_missing_record"] or "none"],
               ["references used on more than one line", len(r["references_used_on_more_than_one_line"])],
               ["records never referenced", len(r["records_never_referenced"])],
               ["reference series vs Schedule 5 series for the item", r["reference_series_vs_schedule_5"]],
               ["Schedule 5 items with no record_ref", r["schedule_5_items_without_reference"]["count"]],
               ["referenced record vs line (area / date)", r["referenced_record_vs_line"]],
           ]), "",
           f"Series differing from Schedule 5: {r['reference_series_differs_from_schedule_5'] or 'none'}", "",
           f"Schedule 5 items without a reference: {r['schedule_5_items_without_reference']['lines'] or 'none'}", "",
           "References used on more than one line:", "",
           _table(["record_ref", "Lines"], [[ref, ", ".join(ls)] for ref, ls in r["references_used_on_more_than_one_line"].items()]), "",
           "## Date relationships", "",
           "Line work dates against contract dates (the original completion date is not by itself a problem: two amendments extend the term).", "",
           _table(["From", "To (exclusive)", "Boundary", "Lines"], [[b["from"], b["to_exclusive"], b["label"], b["lines"]] for b in d["line_work_dates_by_interval"]]), "",
           _table(["Measure", "Value"], [
               ["lines by Contract Year", d["line_work_dates_by_contract_year"]],
               ["lines before commencement", d["lines_before_commencement"]],
               ["lines after original completion (2025-09-27)", d["lines_after_original_completion"]],
               ["lines after extended completion", d["lines_after_extended_completion"]],
           ] + [[k.replace("_", " "), v] for k, v in d["applications"].items()]), "",
           "## Raw arithmetic", "",
           "Billed `amount` compared with `quantity × rate_applied` (both as printed; quantities are integers so the product is exact to the halala). "
           "Whether `rate_applied` is the contract rate is **not** assessed here.", "",
           _table(["Measure", "Value"], [[k.replace("_", " "), v] for k, v in ar["line_amount_vs_quantity_times_rate"].items() if k != "largest_mismatches"]), "",
           _table(["line_ref", "Quantity", "Rate applied", "Amount", "Amount − qty×rate"],
                  [[m["line_ref"], m["quantity"], m["rate_applied"], m["amount"], m["difference"]] for m in ar["line_amount_vs_quantity_times_rate"]["largest_mismatches"]]), "",
           "Application-level identities (as printed):", "",
           _table(["Identity", "Agree", "Differ", "Differences (largest first)"],
                  [[k.replace("_", " "), v["agree"], v["differ"], "; ".join(f"{x['application_no']} {x['difference']}" for x in v["differences"][:10])]
                   for k, v in ar.items() if k != "line_amount_vs_quantity_times_rate"]), ""]
    return "\n".join(out) + "\n"
