"""Civil works draft outputs (outputs/civil_works/). Not the combined submission."""

import csv
import dataclasses
import io
import json
from collections import Counter, defaultdict
from pathlib import Path

from contractor_audit.domains.civil_works.audit.assessment import AuditResult
from contractor_audit.domains.civil_works.audit.categories import CATEGORIES, CATEGORY_INFO
from contractor_audit.domains.civil_works.audit.confidence import LEAST_CERTAIN, grade, switch_info
from contractor_audit.domains.civil_works.audit.options import AUDIT_SWITCHES, WORKING_AUDIT_INTERPRETATION
from contractor_audit.domains.civil_works.interpretation import SWITCHES, WORKING_INTERPRETATION
from contractor_audit.domains.civil_works.audit.review import review_md
from contractor_audit.domains.civil_works.reports import _table
from contractor_audit.domains.civil_works.rounding import cents_to_decimal
from contractor_audit.shared.findings import ConfidenceBand, InvoiceResult

GENERATED = "_Generated by `contractor-audit run --domain civil_works`; do not edit by hand. Civil works draft only — not the combined submission._"
TEMPLATE_COLUMNS = ["invoice_id", "flagged", "error_category", "expected_total_cents", "billed_total_cents", "confidence"]


def _m(cents):
    return "" if cents is None else str(cents_to_decimal(cents))


def invoice_results(result: AuditResult) -> list[InvoiceResult]:
    return [InvoiceResult(a.application_no, a.flagged, a.billed_total_cents, a.expected_total_cents, a.confidence_score,
                          a.primary_category, a.findings) for a in result.applications]


def _json(obj) -> str:
    return json.dumps(obj, ensure_ascii=False, sort_keys=True, default=str)


def findings_jsonl(result: AuditResult) -> str:
    return "".join(_json(dataclasses.asdict(f)) + "\n" for f in result.findings)


def _csv(header, rows) -> str:
    buf = io.StringIO()
    w = csv.writer(buf, lineterminator="\n")
    w.writerow(header)
    w.writerows(rows)
    return buf.getvalue()


def application_audit_csv(result: AuditResult) -> str:
    header = ["application_no", "flagged", "outcome", "total_status", "primary_category", "categories", "billed_total_cents",
              "expected_total_cents", "contract_total_cents", "graded_total_cents", "confidence_band", "confidence",
              "primary_blank_reason", "blank_reasons", "findings", "total_depends_on", "would_flag_under", "outside_total"]
    rows = []
    for a in result.applications:
        rows.append([a.application_no, int(a.flagged), a.outcome, a.total_status, a.primary_category, ";".join(a.categories), a.billed_total_cents,
                     "" if a.expected_total_cents is None else a.expected_total_cents,
                     "" if a.contract_total_cents is None else a.contract_total_cents,
                     "" if a.graded_total_cents is None else a.graded_total_cents,
                     a.confidence.value, a.confidence_score, a.primary_blank_reason, ";".join(a.blank_reasons), len(a.findings),
                     ";".join(sorted({f"{d.switch}={d.alternative}:{d.band.value}" for d in a.total_dependencies if d.band is not ConfidenceBand.HIGH})),
                     ";".join(sorted({f"{d.switch}={d.alternative}:{d.band.value}" for d in a.would_flag_under if d.band is not ConfidenceBand.HIGH})),
                     ";".join(f"{k}:{amt}" for k, amt, _, _ in a.outside_total)])
    return _csv(header, rows)


def draft_predictions_csv(result: AuditResult) -> str:
    rows = [[r.invoice_id, int(r.flagged), r.error_category, "" if r.expected_total_cents is None else r.expected_total_cents,
             r.billed_total_cents, f"{r.confidence:.2f}"] for r in invoice_results(result)]
    return _csv(TEMPLATE_COLUMNS, rows)


# --------------------------------------------------------------------------- sensitivity across readings

def sensitivity_rows(result: AuditResult) -> list[dict]:
    base = result.base
    base_keys = {f.key for f in base.findings}
    base_apps = {f.invoice_id for f in base.findings}
    flagged = {a.application_no for a in result.applications if a.flagged}
    rows = []
    for alt in result.alternatives:
        run = alt.run
        keys = {f.key for f in run.findings}
        apps = {f.invoice_id for f in run.findings}
        lines_changed = sum(1 for ref, v in base.lines.items()
                            if (v.payable_quantity, v.payable_cents) != (run.lines[ref].payable_quantity, run.lines[ref].payable_cents))
        totals_changed = {a for a in base.contract_totals if base.contract_totals[a] != run.contract_totals[a]}
        rows.append({
            "switch": alt.field, "working": alt.working, "alternative": alt.alternative, "grade": alt.band.value,
            "status": switch_info(alt.field).status.value,
            "findings_only_under_working": len(base_keys - keys), "findings_only_under_alternative": len(keys - base_keys),
            "applications_unflagged_by_alternative": len(base_apps - apps), "applications_flagged_by_alternative": len(apps - base_apps),
            "lines_with_payable_or_price_change": lines_changed, "applications_whose_total_changes": len(totals_changed),
            "flagged_applications_whose_corrected_total_changes": len(totals_changed & flagged),
        })
    return rows


def _decision_a(result: AuditResult) -> list[str]:
    out = ["## Decision A — sums settled outside the measured total", "",
           "`expected_total_cents` is the corrected total of what **this** application measures (`application_total`; Clause 43: the total of an "
           "application is the sum of its items). The task schema calls it 'what the invoice should have totalled' and judges `application_total`; "
           "the CSV carries `adjustment` and `retention_released` as separate columns, so the schema and this reading agree.", "",
           "Clause 45A: amount payable = measured total + Clause 31A adjustment − retention + retention released. Those sums are reported as findings and "
           "quantified, and are **not** folded into `expected_total_cents`:", ""]
    rows = []
    for a in result.applications:
        for kind, amt, clause, note in a.outside_total:
            f = next((f for f in a.findings if f.rule == f"adjustments.{kind}"), None)
            rows.append([a.application_no, kind, _m(amt), clause, f.category if f else "(shown correctly)",
                         _m(a.contract_total_cents), _m(a.contract_total_cents + amt) if a.contract_total_cents is not None else "", note])
    out += [_table(["Application", "Sum", "Amount (SAR)", "Clause", "Finding", "Working contract total", "If folded in", "Note"], rows), ""]
    p23 = next((r for r in sensitivity_rows(result) if r["switch"] == "missing_record_consequence"), None)
    if p23:
        valued = sum(1 for f in result.findings for d in f.dependencies if d.switch == "missing_record_consequence" and d.effect == "value_changes")
        out += [f"The P23 reading ('deducted from the next valuation') would leave missing-record lines payable in this application: "
                f"{p23['applications_whose_total_changes']} application totals change and {valued} findings change their monetary effect "
                "(every finding remains); each such total is blanked under the STRICT policy.", ""]
    return out


def _decision_b(result: AuditResult) -> list[str]:
    rows = [r for r in sensitivity_rows(result) if r["switch"] == "rebate_progression"]
    info = switch_info("rebate_progression")
    banded = set(result.base.lines) and {ref for ref, v in result.base.lines.items() if v.payable_quantity < v.billed_quantity}
    reduced = sorted(ref for ref in banded if result.base.lines[ref].contract_billed is not None
                     and result.base.lines[ref].contract_billed.band_allocation is not None)
    out = ["## Decision B — do disallowed quantities advance the rebate bands?", "",
           f"Working reading: `{WORKING_AUDIT_INTERPRETATION.rebate_progression.value}`. {info.default_rationale} "
           "It was chosen from the wording before any comparison with billing, and it is graded MEDIUM (unresolved).", "",
           _table(["Alternative", "Lines changed", "Applications whose total changes", "Findings only under working", "Findings only under alternative",
                   "Flagged applications whose corrected total changes"],
                  [[r["alternative"], r["lines_with_payable_or_price_change"], r["applications_whose_total_changes"], r["findings_only_under_working"],
                    r["findings_only_under_alternative"], r["flagged_applications_whose_corrected_total_changes"]] for r in rows]), "",
           f"Banded lines with any disallowed quantity under the working readings: {', '.join(reduced) or 'none'}.", ""]
    return out


def sensitivity_md(result: AuditResult) -> str:
    rows = sensitivity_rows(result)
    out = ["# Audit sensitivity — civil works", "", GENERATED, "",
           "Each row re-runs the whole audit with one reading flipped. Counts compare that run with the working run. "
           "Grades come from the interpretation registry, not from fit to billing.", "",
           _table(["Switch", "Status", "Grade", "Working", "Alternative", "Findings lost", "Findings gained", "Apps unflagged", "Apps flagged",
                   "Lines changed", "Totals changed", "Flagged totals changed"],
                  [[r["switch"], r["status"], r["grade"], r["working"], r["alternative"], r["findings_only_under_working"],
                    r["findings_only_under_alternative"], r["applications_unflagged_by_alternative"], r["applications_flagged_by_alternative"],
                    r["lines_with_payable_or_price_change"], r["applications_whose_total_changes"], r["flagged_applications_whose_corrected_total_changes"]]
                   for r in rows]), ""]
    out += _decision_a(result) + _decision_b(result)
    return "\n".join(out) + "\n"


# --------------------------------------------------------------------------- summaries

def coverage_md(result: AuditResult) -> str:
    apps = result.applications
    flagged = [a for a in apps if a.flagged]
    blank = [a for a in flagged if a.expected_total_cents is None]
    reasons = Counter(r for a in blank for r in a.blank_reasons)
    by_cat = Counter(f.category for f in result.findings)
    apps_by_cat = Counter(c for a in flagged for c in a.categories)
    dep_findings = defaultdict(set)
    for f in result.findings:
        for d in f.dependencies:
            if d.effect == "finding_absent" and d.band is not ConfidenceBand.HIGH:
                dep_findings[d.switch].add(f.key)
    dep_totals = Counter(sw for a in flagged for sw in {d.switch for d in a.total_dependencies if d.band is not ConfidenceBand.HIGH})
    would = Counter(d.switch for a in apps if not a.flagged for d in {x.switch: x for x in a.would_flag_under if x.band is not ConfidenceBand.HIGH}.values())
    lines = len(result.base.lines)
    out = ["# Audit coverage — civil works", "", GENERATED, "",
           _table(["Measure", "Count"], [
               ["applications audited", len(apps)], ["lines audited", lines], ["site records available", "2169"],
               ["flagged applications", len(flagged)], ["unflagged applications", len(apps) - len(flagged)],
               ["flagged with a corrected total (STRICT policy, published)", len(flagged) - len(blank)],
               ["flagged with a blank corrected total", len(blank)],
               ["flagged with a corrected total under the GRADED policy", sum(a.graded_total_cents is not None for a in flagged)],
               ["findings", len(result.findings)],
               ["lines with unresolved payable quantity or rate", len(result.base.unresolved)],
           ]), "",
           "## Is the application total itself wrong?", "",
           "A flag says the application breaches the contract; `total_status` says whether `application_total` is the wrong number.", "",
           _table(["total_status", "Applications", "Meaning"], [
               [s, sum(a.total_status == s for a in apps), m] for s, m in (
                   ("correct", "not flagged"), ("unchanged", "flagged, but the application total is right (breach without a total effect)"),
                   ("corrected", "flagged, and a different total is published"), ("undetermined", "flagged, corrected total blank"))]), "",
           "## Blank corrected totals by reason", "",
           "Mutually exclusive (`primary_blank_reason`: data gaps first, then the least certain reading, then fixed switch order):", "",
           _table(["Primary reason", "Applications"], sorted(Counter(a.primary_blank_reason for a in blank).items(), key=lambda kv: (-kv[1], kv[0]))), "",
           f"Total: {len(blank)} blank + {len(flagged) - len(blank)} published = {len(flagged)} flagged.", "",
           "All reasons (an application may have several):", "",
           _table(["Reason", "Applications"], [[r, n] for r, n in reasons.most_common()]), "",
           "## Findings by category", "",
           _table(["Category", "Check", "Findings", "Applications", "Meaning"],
                  [[c.value, int(CATEGORY_INFO[c].check), by_cat.get(c.value, 0), apps_by_cat.get(c.value, 0), CATEGORY_INFO[c].meaning] for c in CATEGORIES]), "",
           "## Findings by confidence", "",
           _table(["Band", "Findings", "Flagged applications", "Unflagged applications"],
                  [[b.value, sum(f.confidence is b for f in result.findings), sum(a.confidence is b for a in flagged),
                    sum(a.confidence is b for a in apps if not a.flagged)] for b in ConfidenceBand]), "",
           "## Dependence on unresolved readings", "",
           _table(["Reading", "Grade", "Findings that disappear under the alternative", "Flagged totals that change", "Unflagged applications it would flag"],
                  [[s, grade(s).value, len(dep_findings.get(s, ())), dep_totals.get(s, 0), would.get(s, 0)]
                   for s in [x.field for x in SWITCHES + AUDIT_SWITCHES] if grade(s) is not ConfidenceBand.HIGH]), "",
           "Text-resolved readings (grade HIGH) are also re-run; see `sensitivity.md`.", ""]
    return "\n".join(out) + "\n"


def uncertainty_md(result: AuditResult) -> str:
    out = ["# Uncertainty report — civil works", "", GENERATED, "",
           "Every flagged application whose corrected total is blank, or whose confidence is below HIGH, and every unflagged application an "
           "unresolved reading would flag. Nothing is hidden: a blank total means the figure depends on something the contract or data does not settle.", "",
           "## Flagged, total blank or confidence below HIGH", ""]
    rows = []
    for a in result.applications:
        if a.flagged and (a.expected_total_cents is None or a.confidence is not ConfidenceBand.HIGH):
            rows.append([a.application_no, a.primary_category, a.confidence.value, _m(a.billed_total_cents), _m(a.contract_total_cents),
                         _m(a.graded_total_cents), "; ".join(a.blank_reasons) or "—",
                         "; ".join(sorted({f"{d.switch}={d.alternative}" for f in a.findings for d in f.dependencies
                                           if d.effect == "finding_absent" and d.band is not ConfidenceBand.HIGH})) or "—"])
    out += [_table(["Application", "Primary category", "Confidence", "Billed", "Working contract total", "GRADED total", "Blank because",
                    "Flag depends on"], rows), "",
            "## Unflagged, but an unresolved reading would flag it", ""]
    grouped = defaultdict(list)
    for a in result.applications:
        if not a.flagged:
            key = tuple(sorted({f"{d.switch}={d.alternative}" for d in a.would_flag_under if d.band is not ConfidenceBand.HIGH}))
            if key:
                grouped[key].append(a.application_no)
    out += [_table(["Reading(s)", "Applications", "Examples"], [[", ".join(k), len(v), ", ".join(v[:8]) + (" ..." if len(v) > 8 else "")]
                                                              for k, v in sorted(grouped.items(), key=lambda kv: -len(kv[1]))]), "",
            "## Readings graded LOW", "", ", ".join(sorted(LEAST_CERTAIN)) + ".", ""]
    return "\n".join(out) + "\n"


def audit_summary_md(result: AuditResult) -> str:
    apps = result.applications
    flagged = [a for a in apps if a.flagged]
    out = ["# Audit summary — civil works", "", GENERATED, "",
           f"{len(apps)} applications and {len(result.base.lines)} lines audited against CW-2025-0417-CIV under the working readings "
           f"(`interpretation_matrix.md`; audit readings in `docs/civil_works/decision_log.md`). "
           f"**{len(flagged)} flagged** ({len(flagged) / len(apps):.1%}); {sum(a.expected_total_cents is not None for a in flagged)} with a published corrected total.", "",
           "Working readings: " + ", ".join(f"`{k}={v}`" for k, v in {**WORKING_INTERPRETATION.label(), **WORKING_AUDIT_INTERPRETATION.label()}.items()) + ".", "",
           "## Flagged applications", "",
           _table(["Application", "Categories", "Billed (SAR)", "Corrected (SAR)", "Confidence", "Blank because"],
                  [[a.application_no, ", ".join(a.categories), _m(a.billed_total_cents), _m(a.expected_total_cents) or "blank",
                    f"{a.confidence.value} ({a.confidence_score})", "; ".join(a.blank_reasons)] for a in flagged]), "",
           "## Findings", "",
           "Each finding: what was billed → the record → the contract provision → the expected value → the comparison. Full evidence, "
           "pricing traces, citations and dependencies are in `findings.jsonl`.", ""]
    for a in flagged:
        out += [f"### {a.application_no}", ""]
        for f in a.findings:
            deps = sorted({f"{d.switch}={d.alternative} ({d.band.value})" for d in f.dependencies if d.effect == "finding_absent"})
            out += [f"- **{f.category}** ({f.confidence.value}) {f.line_ref or ''} — {f.message} "
                    f"[{', '.join(c.reference + (f' p.{c.page}' if c.page else '') for c in f.citations)}]"
                    + (f" Impact {_m(f.impact_cents)}." if f.impact_cents is not None else "")
                    + (f" Depends on: {', '.join(deps)}." if deps else "")]
        out += [""]
    return "\n".join(out) + "\n"


def write_outputs(result: AuditResult, out_dir: Path) -> list[Path]:
    out_dir.mkdir(parents=True, exist_ok=True)
    files = {
        "findings.jsonl": findings_jsonl(result),
        "application_audit.csv": application_audit_csv(result),
        "draft_predictions.csv": draft_predictions_csv(result),
        "audit_summary.md": audit_summary_md(result),
        "coverage.md": coverage_md(result),
        "uncertainty_report.md": uncertainty_md(result),
        "sensitivity.md": sensitivity_md(result),
        "review.md": review_md(result),
    }
    written = []
    for name, text in files.items():
        path = out_dir / name
        path.write_text(text, encoding="utf-8", newline="\n")
        written.append(path)
    return written
