"""Phase 4 review of the civil works audit, generated from the audit itself (outputs/civil_works/review.md).

Everything here is recomputed from the audit result, the contract extraction and the Phase 2 engine,
so the review cannot drift from what the audit does. It checks the audit; it never changes it.
"""

from collections import Counter, defaultdict
from decimal import Decimal

from contractor_audit.domains.civil_works.audit.categories import (CATEGORIES, CATEGORY_INFO, CATEGORY_PRECEDENCE,
                                                                   NO_CONSEQUENCE_CATEGORIES, PRIMARY_TIERS, Category)
from contractor_audit.domains.civil_works.pricing import PricingEngine
from contractor_audit.domains.civil_works.reports import _table
from contractor_audit.domains.civil_works.rounding import cents_to_decimal, round_built_up_rate
from contractor_audit.domains.civil_works.valuation import line_context
from contractor_audit.shared.findings import Check, ConfidenceBand

GENERATED = "_Generated by `contractor-audit run --domain civil_works`; do not edit by hand._"
T_RULES, T_PRICE, T_REAL = "audit/test_rules.py", "audit/test_pricing_rules.py", "audit/test_real_audit.py"

# The twelve guideline checks mapped to what implements them. Tests are named so a reader can open them.
CHECKLIST = (
    (Check.CONTRACT_MATCH, "reference, issuer and period", "rules/contract_reference.py; rules/period.py",
     ("contract_reference_mismatch", "work_after_final_completion"), "Agreement p.1; A2 2.1",
     f"{T_RULES}::test_contract_reference_and_issuer"),
    (Check.CONTRACT_LIVE, "contract live on the work dates, term as extended", "rules/period.py",
     ("work_outside_contract_period", "work_after_final_completion"), "Agreement p.1; A1 1.1; A2 2.1",
     f"{T_RULES}::test_final_completion_boundary; test_work_before_commencement_is_not_payable_and_needs_no_rate"),
    (Check.INVOICE_WINDOW, "raised inside its window, after the period closed", "rules/period.py",
     ("application_timing", "application_period_misstated", "line_outside_application_period"), "40; 41",
     f"{T_RULES}::test_submission_window; test_period_misstated_and_line_outside_period"),
    (Check.RECORD_PRESENT, "every line has its record, signed as the contract requires", "rules/records.py",
     ("missing_record", "unsigned_record", "record_line_mismatch"), "Sch 5; 13; 46; 47; 47A; P22; P23",
     f"{T_RULES}::test_missing_record_and_nonexistent_record; test_unsigned_record; test_record_for_another_area_or_date"),
    (Check.RECORDED_QUANTITY, "quantities are the recorded ones (payable up to the record)", "rules/quantity.py",
     ("quantity_exceeds_record",), "47; 6A; 33; 33A; 47A; guideline 5",
     f"{T_RULES}::test_quantity_above_record; test_first_hour_rule; test_survey_tolerance; test_week_needs_five_days"),
    (Check.ITEM_IDENTIFIED, "each line identified against a priced item", "rules/item_identity.py",
     ("item_record_mismatch", "unit_mismatch", "item_not_in_contract"), "26; 47A; P24; Sch 1",
     f"{T_RULES}::test_record_of_wrong_series_or_item; test_unit_mismatch_rejects_the_line"),
    (Check.RATE_IN_FORCE, "rate in force on the work date, instruments in order issued", "rules/rates.py (+ Phase 2 rates.py)",
     ("unit_rate_mismatch",), "27; 28; Schedule of Variations; S1-A3",
     f"{T_PRICE}::test_wrong_zone_factor; test_superseded_amendment_rate; test_amendment_boundary_day_before_is_clean"),
    (Check.ADJUSTMENTS, "adjustments in contract order and rounding; discounts from their date", "rules/rates.py; rules/adjustments.py; rules/arithmetic.py",
     ("rebate_incorrectly_applied", "discount_incorrectly_applied", "adjustment_missing", "adjustment_incorrectly_applied", "retention_incorrect"),
     "27; 28; Sch 4 Part 3; S2 2.2; A2 2.3; 31A; 45; 45A",
     f"{T_PRICE}::test_discount_omitted; test_rebate_band_omitted; test_retro_adjustment_missing_and_incorrect; test_retention_incorrect"),
    (Check.LIMITS, "caps, exclusion windows, once-only items, minimum charges", "rules/limits.py; rules/exclusions.py",
     ("daily_limit_exceeded", "exclusion_window_violation"), "31; Sch 4 Parts 4-5; 32; P19; P21",
     f"{T_RULES}::test_daily_limit; test_exclusion_window_boundary; test_p21_traffic_management_on_surfacing_day"),
    (Check.NOT_DUPLICATED, "nothing billed twice, within the invoice or against an earlier one", "rules/duplicates.py; rules/quantity.py",
     ("duplicate_line", "duplicate_record"), "44; 47A; guideline 10",
     f"{T_RULES}::test_duplicate_line_same_item_area_date; test_one_week_record_billed_twice_is_a_duplicate_record"),
    (Check.ARITHMETIC, "line amounts, subtotal, deductions reconcile", "rules/arithmetic.py; rules/rates.py (band-split amounts)",
     ("line_total_arithmetic", "application_total_mismatch"), "28; 43; 45A",
     f"{T_PRICE}::test_line_arithmetic_and_rate_on_one_line; test_application_total_and_net; test_band_split_line_is_judged_on_amount_only"),
    (Check.OUTCOME_RECORDED, "outcome written down: pass / query / part-reject, clause, payable figure, what is undetermined",
     "assessment.py; reports.py", (), "guideline 12",
     f"{T_REAL}::test_policy_invariants; test_draft_predictions_schema; test_every_finding_is_traceable"),
)

CATEGORY_TESTS = {
    "contract_reference_mismatch": f"{T_RULES}::test_contract_reference_and_issuer",
    "work_outside_contract_period": f"{T_RULES}::test_work_before_commencement_is_not_payable_and_needs_no_rate",
    "work_after_final_completion": f"{T_RULES}::test_final_completion_boundary",
    "application_timing": f"{T_RULES}::test_submission_window",
    "application_period_misstated": f"{T_RULES}::test_period_misstated_and_line_outside_period",
    "line_outside_application_period": f"{T_RULES}::test_period_misstated_and_line_outside_period",
    "missing_record": f"{T_RULES}::test_missing_record_and_nonexistent_record",
    "unsigned_record": f"{T_RULES}::test_unsigned_record",
    "record_line_mismatch": f"{T_RULES}::test_record_for_another_area_or_date",
    "item_record_mismatch": f"{T_RULES}::test_record_of_wrong_series_or_item",
    "unit_mismatch": f"{T_RULES}::test_unit_mismatch_rejects_the_line",
    "item_not_in_contract": "audit/test_freeze.py::test_item_not_in_contract",
    "quantity_exceeds_record": f"{T_RULES}::test_quantity_above_record",
    "duplicate_record": f"{T_RULES}::test_one_week_record_billed_twice_is_a_duplicate_record",
    "duplicate_line": f"{T_RULES}::test_duplicate_line_same_item_area_date",
    "daily_limit_exceeded": f"{T_RULES}::test_daily_limit",
    "exclusion_window_violation": f"{T_RULES}::test_exclusion_window_boundary",
    "unit_rate_mismatch": f"{T_PRICE}::test_wrong_zone_factor",
    "rebate_incorrectly_applied": f"{T_PRICE}::test_rebate_band_omitted",
    "discount_incorrectly_applied": f"{T_PRICE}::test_discount_omitted",
    "line_total_arithmetic": f"{T_PRICE}::test_line_arithmetic_and_rate_on_one_line",
    "application_total_mismatch": f"{T_PRICE}::test_application_total_and_net",
    "adjustment_missing": f"{T_PRICE}::test_retro_adjustment_missing_and_incorrect",
    "adjustment_incorrectly_applied": f"{T_PRICE}::test_retro_adjustment_missing_and_incorrect",
    "retention_incorrect": f"{T_PRICE}::test_retention_incorrect",
}

# What the contract says the payable quantity is after each breach (section 10 of the Phase 4 brief).
QUANTITY_CONSEQUENCES = (
    ("unit_mismatch", "26: 'rejected in its entirety rather than converted'", "A: payable 0"),
    ("work_after_final_completion", "A2 2.1: work after the extended Date for Completion 'is not' measurable and payable", "A: payable 0"),
    ("work_outside_contract_period", "Agreement: works commence 05 January 2025; no rate is in force earlier", "A: payable 0"),
    ("line_outside_application_period", "41: 'no item shall be included in an application whose stated period does not include' its day", "A: payable 0 in this application"),
    ("missing_record / record_line_mismatch / item_record_mismatch", "46: 'not payable in any valuation until that record has been delivered' vs P23: 'deducted from the next valuation'",
     "unresolved: `missing_record_consequence` (total blank)"),
    ("unsigned_record", "47 / P22: both signatures form part of the record", "unresolved: `unsigned_record` (total blank)"),
    ("quantity_exceeds_record (record)", "47 + guideline 5: 'payable up to the record, not at all above it'", "A: payable = recorded quantity"),
    ("quantity_exceeds_record (hours)", "6A: 'the quantity measured is one hour fewer'", "A: payable = hours attended - 1"),
    ("quantity_exceeds_record (survey)", "33A: above 2% 'payable at the surveyed quantity only' (33: exactly)", "A under either reading; reading measured (`survey_quantity_rule`)"),
    ("quantity_exceeds_record (week)", "47A: 'a week is measurable only where the record shows work on not fewer than five days'", "A: payable 0 weeks"),
    ("duplicate_line", "44: 'the later measurement shall be disallowed in full'", "A: payable 0 for the later; which is later is `measurement_order`"),
    ("duplicate_record", "44 / 47A: a record evidences its quantity once", "A: allowance used in measurement order; `measurement_order`"),
    ("daily_limit_exceeded", "31: 'no more than that quantity is measurable ... per work area, per day'; the excess 'is not payable'",
     "A: payable = the limit. Clause 44 already disallows any second measurement of the same item, work area and day, so the "
     "cap always binds one line; a defensive guard would blank the total (`limit_allocation_unresolved`) if that ever failed"),
    ("exclusion_window_violation", "32 / P19 / P21: 'not measurable'", "A: payable 0; same-day inclusion is `exclusion_window`"),
)


def _m(cents):
    return "" if cents is None else str(cents_to_decimal(cents))


def _lines(result):
    return {l.line_ref: l for l in result.data.lines}


# --------------------------------------------------------------------------- sections

def _checklist(result) -> list[str]:
    counts = Counter(f.category for f in result.findings)
    rows = [[int(c), text, rules, ", ".join(cats) or "—", clauses, tests, sum(counts.get(x, 0) for x in cats) if cats else "all 900 rows"]
            for c, text, rules, cats, clauses, tests in CHECKLIST]
    return ["## 1. Guideline checklist", "",
            "Every check in `INVOICE_AUDIT_GUIDELINES.md` mapped to its implementation. Output coverage: every finding is in "
            "`findings.jsonl`; every application is a row of `application_audit.csv` and `draft_predictions.csv`.", "",
            _table(["Check", "Requirement", "Implemented in", "Categories", "Contract", "Tests", "Findings"], rows), "",
            "Check 9 'once-only items and minimum charges': the contract has no minimum-charge clause; its only once-only provision is "
            "Schedule 8's lump-sum preliminaries ('valued once'), and no application bills a Schedule 8 or any other non-Schedule 1 code. "
            "Any such line would be caught by `item_not_in_contract`.", ""]


def _category_matrix(result) -> list[str]:
    counts = Counter(f.category for f in result.findings)
    deps = defaultdict(set)
    for f in result.findings:
        for d in f.dependencies:
            if d.effect == "finding_absent":
                deps[f.category].add(f"{d.switch} ({d.band.value})")
    gained = defaultdict(set)
    base_keys = {f.key for f in result.base.findings}
    for a in result.alternatives:
        for f in a.run.findings:
            if f.key not in base_keys and a.band is not ConfidenceBand.HIGH:
                gained[f.category].add(f"{a.field} ({a.band.value})")
    effect = {c: ("no (breach only)" if c in NO_CONSEQUENCE_CATEGORIES or c in (Category.CONTRACT_REFERENCE_MISMATCH,)
                  else "outside the total" if c in (Category.ADJUSTMENT_MISSING, Category.ADJUSTMENT_INCORRECTLY_APPLIED, Category.RETENTION_INCORRECT)
                  else "blanks it" if c is Category.ITEM_NOT_IN_CONTRACT else "yes") for c in CATEGORIES}
    rows = [[c.value, int(CATEGORY_INFO[c].check), "; ".join(CATEGORY_INFO[c].clauses), CATEGORY_TESTS[c.value], counts.get(c.value, 0),
             effect[c], "; ".join(sorted(deps[c.value])) or "—", "; ".join(sorted(gained[c.value])) or "—"] for c in CATEGORIES]
    zero = [c.value for c in CATEGORIES if not counts.get(c.value)]
    return ["## 2. Category matrix", "",
            _table(["Category", "Check", "Clauses", "Test", "Findings", "Affects total", "Finding disappears under", "Extra findings appear under"], rows), "",
            f"Zero-occurrence categories ({len(zero)}): {', '.join(zero)}. Each is implemented and exercised by the synthetic test named above. "
            "`service_not_contracted_on_date` is not a civil works concept: no Schedule 1 item is limited to a date range, and the term itself is "
            "checked by `work_outside_contract_period` / `work_after_final_completion`; an item with no Schedule 1 rate is `item_not_in_contract`.", ""]


def _adversarial(result) -> list[str]:
    fs = result.findings
    by_line = defaultdict(list)
    for f in fs:
        if f.line_ref:
            by_line[f.line_ref].append(f)
    multi = {r: v for r, v in by_line.items() if len(v) > 1}
    same_cat = [(r, c) for r, v in by_line.items() for c, n in Counter(f.category for f in v).items() if n > 1]
    arith_and_rate = [r for r, v in multi.items() if {"line_total_arithmetic", "unit_rate_mismatch"} <= {f.category for f in v}]
    no_citation = [f.key for f in fs if not f.citations or not all(c.page for c in f.citations)]
    no_line_ev = [f.key for f in fs if f.line_ref and (not f.evidence or f.evidence[0].kind != "billed_line")]
    reading = [f for f in fs if any(d.effect == "finding_absent" for d in f.dependencies)]
    rows = [[f.invoice_id, f.line_ref or "—", f.category, f.confidence.value,
             "; ".join(sorted({f"{d.switch}={d.alternative} ({d.band.value})" for d in f.dependencies if d.effect == "finding_absent"}))] for f in reading]
    mrows = [[r, ", ".join(f.category for f in v), "independent rules" if len({f.rule.split(".")[0] for f in v}) == len(v) else "same rule family"]
             for r, v in sorted(multi.items())]
    kinds = Counter("changes the total" if f.affects_total else "outside the total" if f.outside_total else "no monetary consequence" for f in fs)
    return ["## 3. Adversarial review of the flags", "",
            _table(["Check", "Result"], [
                ["findings reviewed", len(fs)], ["flagged applications", sum(a.flagged for a in result.applications)],
                ["findings without a paged citation", len(no_citation)], ["line findings without the billed line as first evidence", len(no_line_ev)],
                ["same line reported twice under one category", len(same_cat)],
                ["lines with an arithmetic finding caused by a rate finding", "0 by construction: arithmetic compares amount with quantity x billed rate, "
                 f"independent of the contract rate; lines with both: {', '.join(arith_and_rate) or 'none'}"],
                ["monetary type", ", ".join(f"{k}: {v}" for k, v in sorted(kinds.items()))],
            ]), "",
            "Lines with more than one finding (each checked for a shared root cause; the only shared-cause case found — PA-00170-04, whose "
            "pressure-test record is both the wrong series and for another area and date — is now reported once, as `item_record_mismatch`):", "",
            _table(["Line", "Findings", "Assessment"], mrows) if mrows else "none", "",
            "Findings that exist only because of a working reading (each carries the dependency and its grade):", "",
            _table(["Application", "Line", "Category", "Confidence", "Disappears under"], rows), ""]


def _unflagged(result) -> list[str]:
    un = [a for a in result.applications if not a.flagged]
    combos = Counter(tuple(sorted({d.switch for d in a.would_flag_under if d.band is not ConfidenceBand.HIGH})) for a in un)
    by_switch = Counter(s for a in un for s in {d.switch for d in a.would_flag_under if d.band is not ConfidenceBand.HIGH})
    high = [a for a in un if a.confidence is ConfidenceBand.HIGH]
    violations = [a.application_no for a in high if any(d.band is not ConfidenceBand.HIGH for d in a.would_flag_under)]
    text_only = sum(1 for a in high if a.would_flag_under)
    return ["## 4. Unflagged applications", "",
            _table(["Would be flagged under (non-HIGH readings)", "Applications"],
                   [[", ".join(k) or "no unresolved reading", v] for k, v in sorted(combos.items(), key=lambda kv: (-kv[1], kv[0]))]), "",
            _table(["Reading", "Unflagged applications it would flag"], sorted(by_switch.items(), key=lambda kv: (-kv[1], kv[0]))), "",
            f"{len(high)} unflagged applications are HIGH. None of them is flagged by any unresolved or evidence-dependent reading "
            f"(violations: {violations or 'none'}). {text_only} of them would be flagged only by a text-resolved alternative "
            "(e.g. Schedule 2B read as SAR), which the contract text rules out.", ""]


def _duplicates(result) -> list[str]:
    lines, data = _lines(result), result.data
    apps = {a.application_no: a for a in data.applications}
    alt = next(a for a in result.alternatives if a.field == "measurement_order")
    alt_keys = {f.key for f in alt.run.findings}
    groups = defaultdict(list)
    for l in data.lines:
        if l.record_ref:
            groups[("record", l.record_ref)].append(l)
        groups[("item_area_date", l.item_code, l.site, l.work_date)].append(l)
    rows = []
    for key, members in sorted(groups.items(), key=lambda kv: str(kv[0])):
        if len(members) < 2:
            continue
        if key[0] == "record" and not any(f.category == "duplicate_record" and f.line_ref in {m.line_ref for m in members} for f in result.base.findings + alt.run.findings):
            continue
        by_sub = sorted(members, key=lambda l: (apps[l.application_no].application_date, l.application_no, l.line_no))
        by_num = sorted(members, key=lambda l: (l.application_no, l.line_no))
        dup_rules = {"duplicate_record", "duplicate_line"}
        working = sorted(f.line_ref for f in result.base.findings if f.category in dup_rules and f.line_ref in {m.line_ref for m in members})
        alternative = sorted(f.line_ref for f in alt.run.findings if f.category in dup_rules and f.line_ref in {m.line_ref for m in members})
        totals = sorted({m.application_no for m in members if result.base.contract_totals[m.application_no] != alt.run.contract_totals[m.application_no]})
        rows.append([key[1] if key[0] == "record" else f"{key[1]} {key[2]} {key[3]}",
                     "; ".join(f"{m.line_ref} (submitted {apps[m.application_no].application_date}, work {m.work_date})" for m in members),
                     by_sub[0].line_ref, by_num[0].line_ref, ", ".join(working), ", ".join(alternative),
                     "yes" if working != alternative else "no", ", ".join(totals) or "none"])
    changed = sum(r[6] == "yes" for r in rows)
    return ["## 5. Duplicate groups and the 'later measurement'", "",
            "Clause 44 disallows 'the later measurement'. The contract does not define 'later'; the working reading is the later submission "
            "(guideline 10: billed twice 'against an earlier one'), the alternative the higher application number. A third reading (later work "
            "date) has no textual anchor in Clause 44 and is not modelled.", "",
            _table(["Group", "Lines", "Kept (by submission)", "Kept (by number)", "Refused (working)", "Refused (alternative)", "Flag moves", "Totals change"], rows), "",
            f"{len(rows)} groups; the refused line moves between applications in {changed} of them. The dependency stays measured "
            "(`measurement_order`, MEDIUM) and every affected total is blank.", ""]


def _exclusions(result) -> list[str]:
    data = result.data
    rows = []
    by_area = defaultdict(list)
    for l in data.lines:
        by_area[l.site].append(l)
    alt = next(a for a in result.alternatives if a.field == "exclusion_window")
    for area, ls in sorted(by_area.items()):
        fills = [l for l in ls if l.item_code == "A.14.010"]
        backs = [l for l in ls if l.item_code == "A.14.020"]
        for b in backs:
            for f in fills:
                gap = (b.work_date - f.work_date).days
                if abs(gap) <= 3:
                    work = any(x.line_ref == b.line_ref and x.category == "exclusion_window_violation" for x in result.base.findings)
                    other = any(x.line_ref == b.line_ref and x.category == "exclusion_window_violation" for x in alt.run.findings)
                    rows.append([area, f.line_ref, b.line_ref, gap, "excluded" if work else "payable", "excluded" if other else "payable"])
    p21 = [f for f in result.base.findings if f.rule == "exclusions.p21_same_day"]
    return ["## 6. Exclusion windows", "",
            "Sch 4 Part 5 and Clause 32: A.14.020 'is not measurable within the stated period following measurement of' A.14.010 on the same work "
            "area (2 days). Direction: only after the A.14.010 measurement ('following'); a backfill before the fill is unaffected. Day +2 is inside "
            "the window under both readings; the open question is day 0 (P19 'within two days of' vs Clause 32 'following'). The excluded item "
            "(A.14.020) loses payment; the trigger (A.14.010) does not.", "",
            _table(["Work area", "A.14.010", "A.14.020", "Days after", "Working (same day included)", "Alternative (same day excluded)"], rows)
            if rows else "No A.14.010 / A.14.020 pairs within 3 days.", "",
            f"P21 (E.51.020 on a surfacing day): {len(p21)} findings.", ""]


def _split_lines(result) -> list[str]:
    terms = result.data.terms
    engine = PricingEngine(terms)
    lines, apps = _lines(result), {a.application_no: a for a in result.data.applications}
    checked = amount_ok = flagged_rate = 0
    problems = []
    for ref, v in sorted(result.base.lines.items()):
        cb = v.contract_billed
        if cb is None or not cb.is_split:
            continue
        checked += 1
        line = lines[ref]
        alloc = cb.band_allocation
        edges = {b.end for b in terms.bands[line.item_code] if b.end is not None}
        # Independent recomputation of the segmentation and each segment's rate.
        pre = engine.pre_band_rate(line_context(line, apps[line.application_no], engine.interp))
        total = Decimal(0)
        seg_ok = sum(s.quantity for s in alloc.slices) == line.quantity
        for s, part in zip(alloc.slices, cb.parts):
            seg_ok &= s.cumulative_to - s.cumulative_from == s.quantity
            rate = pre.value * s.percent_of_rate / 100
            for _, pct in pre.discount_factors:
                rate = rate * (1 - pct / 100)
            seg_ok &= round_built_up_rate(rate) == part.rate
            total += s.quantity * part.rate
        seg_ok &= all(Decimal(s.cumulative_to) in edges for s in alloc.slices[:-1])
        seg_ok &= int(total * 100) == cb.amount_cents
        if not seg_ok:
            problems.append(ref)
        amount_ok += line.amount_cents == cb.amount_cents
        flagged_rate += any(f.line_ref == ref and f.rule == "rates.unit_rate" for f in result.findings)
    split_findings = [f for f in result.findings if f.rule == "rates.band_split_amount"]
    return ["## 7. Band-split lines", "",
            _table(["Check", "Result"], [
                ["billed lines the contract divides at a band edge", checked],
                ["segmentation (slices sum to the quantity, cut exactly at band edges), segment rates (pre-band rate x band % x discounts, rounded once) and amount recomputed outside the ledger and equal to the engine", checked - len(problems)],
                ["recomputation mismatches", ", ".join(problems) or "none"],
                ["billed amount equals the contract split amount", amount_ok],
                ["split lines judged on their printed (pre-rebate) rate", flagged_rate],
                ["split-line amount findings", ", ".join(f"{f.line_ref} ({f.category})" for f in split_findings) or "none"],
            ]), ""]


def _totals(result) -> list[str]:
    engine = PricingEngine(result.data.terms)
    lines, apps = _lines(result), {a.application_no: a for a in result.data.applications}
    flagged = [a for a in result.applications if a.flagged]
    published = [a for a in flagged if a.expected_total_cents is not None]
    reconstructed, issues = 0, []
    for a in published:
        total = 0
        for l in result.data.lines:
            if l.application_no != a.application_no:
                continue
            v = result.base.lines[l.line_ref]
            if v.payable_quantity == 0:
                continue
            alloc = v.contract_payable.band_allocation
            total += engine.price(line_context(l, apps[l.application_no], engine.interp), v.payable_quantity, alloc).amount_cents
        ok = total == a.expected_total_cents and not any(d.band is not ConfidenceBand.HIGH for d in a.total_dependencies)
        reconstructed += ok
        if not ok:
            issues.append(a.application_no)
    blank = [a for a in flagged if a.expected_total_cents is None]
    excl = Counter(a.primary_blank_reason for a in blank)
    return ["## 8. Corrected totals", "",
            _table(["Measure", "Count"], [
                ["flagged applications", len(flagged)], ["published corrected totals", len(published)], ["blank corrected totals", len(blank)],
                ["published totals re-priced line by line from their payable quantities (fresh engine instance, same contract rules) and matched", reconstructed],
                ["published totals failing the check", ", ".join(issues) or "none"],
                ["published totals equal to the billed total (breach without a total effect)", sum(a.total_status == "unchanged" for a in published)],
            ]), "",
            "Blank totals, mutually exclusive primary reason:", "",
            _table(["Primary reason", "Applications"], sorted(excl.items(), key=lambda kv: (-kv[1], kv[0]))), "",
            "Unflagged rows carry `expected_total_cents = billed_total_cents`: the task asks for all 900 rows and a `0` is a claim that the total is right.", ""]


def _topics(result) -> list[str]:
    raw = result.data.raw_extraction
    s2a, clauses = raw["schedule_2a"], {c["id"]: c for c in raw["clauses"]}
    rows = {r["switch"] + "=" + r["alternative"]: r for r in _sens(result)}

    def eff(key):
        r = rows[key]
        return (f"{r['lines_with_payable_or_price_change']} lines, {r['applications_whose_total_changes']} totals, "
                f"{r['applications_flagged_by_alternative']} unflagged applications would be flagged, {r['findings_only_under_working']} findings lost")
    return ["## 9. Reviews of the unresolved readings", "",
            "### Indexation (Schedule 2A, Clause 29A, Appendix B)", "",
            f"- Schedule 2A (p.21): \"{s2a['source_text']}\"",
            f"- Clause 29A (p.32): \"{clauses['29A']['text']}\"",
            "- Automatic: yes (the Schedule 1 rate 'is not payable as it stands'). External data: none — the Site Materials Index is printed for every "
            "month 2025-01 to 2026-12 and the base is 100.00. Compounding: no (each month is taken against the fixed base). Effect: it replaces the "
            "unit rate before the Clause 27 build-up.",
            "- Against it: the Appendix B worked example prices C.31.010 on 13/05/2025 at 86.20 x 1.06 = 91.37, unindexed.",
            "- Weight: Clause 2 makes 'Schedules 1 to 5 and Appendix A' the whole agreement; Schedule 2A sits within Schedules 1 to 5, Appendix B does "
            "not. That favours 29A more strongly than recorded in Phase 2, but the conflict is inside the document, so the reading stays UNRESOLVED "
            "(MEDIUM) and is not upgraded in this freeze.",
            f"- Alternative effect: {eff('indexed_rate_method=appendix_b_unindexed')}. Production reading (29A) remains justified.", "",
            "### Monthly rates (S1 1.2 for D.41.020, A2 2.2 for E.54.010)", "",
            "- Wording: 'The rate payable for a measured quantity is the rate published for the calendar month in which the work was executed. Where work "
            "is executed in a month later than the last month stated below, the rate last published applies until it is superseded.'",
            "- Payable amount = quantity x rate; no daily or pro-rata treatment is stated; the month of the work date selects the rate.",
            "- Open: whether zone factor / night uplift apply on top (base rate) or not (final rate). E.54.010 is Series E with no uplift, band or "
            "discount, so only D.41.020 (May-November 2025) is affected.",
            f"- Alternative effect: {eff('monthly_rate_treatment=final_rate')}. Stays UNRESOLVED (MEDIUM).", "",
            "### Backdated adjustment (Amendment No. 3, Clause 31A)", "",
            f"- Clause 31A (p.32): \"{clauses['31A']['text']}\"",
            "- Trigger: A3 issued 2026-05-12; effective 2025-11-01 (retrospective). The difference is 'a single adjustment' on one application, i.e. the "
            "`adjustment` column, not `application_total` (Clause 45A: payable = measured total + 31A adjustment - retention + release).",
            "- Open: 'on or after' the issue date (31A) vs 'after' (A3 recital). Three applications are dated 2026-05-12.",
            f"- Alternative effect: {eff('retro_adjustment_trigger=after_issue')}. PA-00006 carries the finding under the working reading, PA-00443 "
            "under the alternative; the finding is LOW.", "",
            "### Retention and its release", "",
            "- Retention (Clause 45) and the release (Clause 45A) are separate columns (`retention`, `retention_released`), outside `application_total`.",
            "- PA-00678, the first application after 2026-09-30, shows no release: a contractual error (`adjustment_missing`) whose correction does not "
            "change `application_total` (`total_status` says whether the total itself is wrong).", ""]


def _sens(result):
    from contractor_audit.domains.civil_works.audit.reports import sensitivity_rows
    return sensitivity_rows(result)


def _consequences() -> list[str]:
    return ["## 10. Quantity and cap consequences", "",
            "A: the contract fixes the payable quantity after the breach, so the total can be reconstructed. "
            "B: the contract states the limit but not the corrected quantity, so the breach is flagged and the total left blank.", "",
            _table(["Rule", "Contract", "Consequence"], [list(r) for r in QUANTITY_CONSEQUENCES]), ""]


def _precedence() -> list[str]:
    return ["## 11. Primary category precedence", "",
            "The row's `error_category` is the finding with the lowest (tier, category precedence, line, rule). Monetary size is never used.", "",
            _table(["Tier", "Meaning"], [[k, v] for k, v in PRIMARY_TIERS.items()]), "",
            "Within a tier: " + " > ".join(c.value for c in CATEGORY_PRECEDENCE) + ".", ""]


def review_md(result) -> str:
    out = ["# Civil works audit review (Phase 4 freeze)", "", GENERATED, "",
           "Recomputed from the audit on every run; see `docs/civil_works/decision_log.md` for the decisions it supports.", ""]
    for section in (_checklist, _category_matrix, _adversarial, _unflagged, _duplicates, _exclusions, _split_lines, _totals, _topics):
        out += section(result)
    out += _consequences() + _precedence()
    return "\n".join(out) + "\n"
